### ISSUE TITLE
Office Install Toolkit generating improper code for <Updates>

### ISSUE THREAD

**Issue by benjamz** [OfficeDev/Office-IT-Pro-Deployment-Scripts#102]
I have been trying to utilize your very helpful Office365 Install Toolkit msi generator, it was to be a great help in our initial testing of Windows 10/Office2016.

Over many frustrating hours of downloading, modifying and creating MSI's that would all fail in the same manor, I started to have a look at the configuration file being embedded into the MSI with your viewing tab.   When you look at the xml config from your tab view on the final page of the generator, it looks perfect and as should be.

However, when you copy to clipboard and then paste,  it has an error in the coding for the update section.    <Updates Enabled="TRUE" Channel="Current" UpdatePath="\\server\shared\deployment\Office_2016"></Updates>

When I compared this to other information available, it should be this: Office_2016" /> and not Office_2016"></Updates>

I would very much like to utilize your msi builder, but in the meantime I have made my network deployment using ODT methods with properly formatted XML and will hope to have your msi builder available again someday.

**Comment by alex182** [comment]
We have posted a new version of the install toolkit which addressed this issue.  We will leave this issue open for the next 3 days.  If the issue persists please let us know and we will revisit the problem asap.  Thanks!
