### ISSUE TITLE
Install toolkit does not allow creation of setup file without Office suite

### ISSUE THREAD

**Issue by Larryngolog** [OfficeDev/Office-IT-Pro-Deployment-Scripts#105]
I would like to build setup only for Visio / Project, without Office suite. Unfortunately I cannot deselect Office Suite nor modify the XML file. Even if I load the configruation.xml without Office it will still be added during configuration in the wizard.

**Comment by Kaze-tenshu** [comment]
Yes I am having the same problem!

**Comment by alex182** [comment]
We have posted a new version of the install toolkit which addressed this issue.  We will leave this issue open for the next 3 days.  If the issue persists please let us know and we will revisit the problem asap.  Thanks!
