### ISSUE TITLE
When trying to embed installation files:  Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by natephelps** [OfficeDev/Office-IT-Pro-Deployment-Scripts#106]
When trying to generate an installation with embedded installation files I receive a "Object reference not set to an instance of an object" error.  Generating installs without embedded files works fine.

![image](https://cloud.githubusercontent.com/assets/19412369/15330529/d8ffb80c-1c22-11e6-9eed-f8867788a036.png)

**Comment by xtozi** [comment]
I've the same issue!

**Comment by xtozi** [comment]
I found the solution:
1. In the "Download Tab" Select the source location and the version and click on download
2. Finalize the rest of the configuration based on your requirements
3. In the "Generate Tab" check the Embed Office Installation Files checkbox. Note that the Source

**Comment by xtozi** [comment]
I found the solution (works only for 32-Bit):
1. In the "Download Tab" Select the source location and the version and click on download
2. Finalize the rest of the configuration based on your requirements
3. In the "Generate Tab" check the Embed Office Installation Files check box. Note that the Source file path is filled out - the same as the source location - and click on generate.

**Comment by alex182** [comment]
We have posted a new version of the install toolkit which addressed this issue.  We will leave this issue open for the next 3 days.  If the issue persists please let us know and we will revisit the problem asap.  Thanks!

**Comment by natephelps** [comment]
Close...no more error but it's not actually creating the an MSI file when
that option is selected.   EXE file generation works.  MSI generation
results in two files:

One ending in .wxs
One ending in .wixobj

It looks like the EXE file is created as part of the MSI generation process
- but disappears at the end of MSI generation

**Comment by v-rusmit** [comment]
@natephelps We believe the MSI generation issue is caused with an size issue with MSI.  It looks like MSI's are capped at 2GB.  We have posted a new build that will only include Bitness that is selected in the Configuration. So if 32-Bit is selected and the 64-bit files exist in the source file path it will not include them.
