### ISSUE TITLE
On EXE extraction: ERROR: System.IO.IOException: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by natephelps** [OfficeDev/Office-IT-Pro-Deployment-Scripts#109]
Receive the below error output when trying to run the install from EXE installer after extracting files.  I've been able to re-produce the error on 5 Windows 7 systems, but worked on a WIndows 10 system.

C:\Windows\System32>"C:\Program Files (x86)\BigFix Enterprise\BES Client\__BESDa
ta\actionsite\__Download\OfficeProPlus64.exe"
Extracting Install Files...ERROR: System.IO.IOException: Cannot create a file wh
en that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Bo
olean checkHost)
   at InstallOffice.MoveFile(String rootDirectory, String md5Hash, String fileNa
me)
   at InstallOffice.GetEmbeddedItems(String targetDirectory)
   at InstallOffice.Initialize()
   at InstallOffice.RunProgram()
   at InstallOffice.Main(String[] args)

**Comment by johnskydiver** [comment]
I've attempted to recreate the error you've posted here, and I am unable to.  The error stack looks like it comes from an install file created by our toolkit.  Can you provide information on which options you selected on the toolkit.  It would also be helpful to know how you're launching the file, is it via command prompt, or simply right click and choosing run as admin, or is it triggered through an admin means such as SCCM or something else.  Thanks.

**Comment by shaunep** [comment]
I am receiving the exact same error message with the installer files created by the toolkit.

Extracting Install Files...ERROR: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at InstallOffice.MoveFile(String rootDirectory, String md5Hash, String fileName)
   at InstallOffice.GetEmbeddedItems(String targetDirectory)
   at InstallOffice.Initialize()
   at InstallOffice.RunProgram()
   at InstallOffice.Main(String[] args)

Here is what my configuration.xml file looks like:
<Configuration>
  <Add OfficeClientEdition="32" Channel="Deferred">
    <Product ID="O365ProPlusRetail">
      <Language ID="en-us" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" Channel="Deferred" />
  <Display Level="Full" AcceptEULA="True" />
  <Property Name="PinIconsToTaskbar" Value="TRUE" />
  <Property Name="AUTOACTIVATE" Value="0" />
  <Property Name="FORCEAPPSHUTDOWN" Value="FALSE" />
  <Property Name="SharedComputerLicensing" Value="0" />
  <Logging Level="Off" />
</Configuration>

Also, on the generate section of the toolkit, I selected "Embed Office installation files".

I have tried both MSI and EXE as the install type and receive the same error in both cases. Of course for the MSI, it extracts the EXE and then throws the error. I am running the installers as administrator from the command prompt.

**Comment by shaunep** [comment]
I found a workaround, by clearing out the Windows\Temp folder, it seems to resolve the issue.

**Comment by johnskydiver** [comment]
Was able to replicate and resolve the issue.  The fix will be on the next release of the toolkit.  As a work around for the time being, please take the advice of @shaunep  and delete the folder C:\Windows\Temp\OfficeProPlus before attempting to run the generated file.

Thanks everyone for your feedback.
