### ISSUE TITLE
Unable to Exclude OneDrive

### ISSUE THREAD

**Issue by chadmt** [OfficeDev/Office-IT-Pro-Deployment-Scripts#112]
In the Exclude section, one cannot select OneDrive, only Groove (OneDrive for Business), which removes OneDrive for business but leaves the "standard" OneDrive package in place.

![missing onedrive](https://cloud.githubusercontent.com/assets/19294893/15876293/73f9c70e-2cc1-11e6-8bf2-ba73d23f3a35.PNG)

Generate -> Configuration is also non-editable. Leaving no work around.

**Comment by csmallmda** [comment]
This is a problem for us as well. If I import an xml that does exclude onedrive personal, the gui tool removes it.

The gui tool generates MSI's which is great but wont exclude onedrive personal... please add the exclusion of onedrive personal to the gui tool.

**Comment by johnskydiver** [comment]
This issue has been resolved is available via the most current toolkit available for download.
