### ISSUE TITLE
Error in Generate-ODTConfigurationXML.ps1 on line 629

### ISSUE THREAD

**Issue by kgeudens** [OfficeDev/Office-IT-Pro-Deployment-Scripts#113]
When you have application like notepad++ installed, the script fails becuase of the logical expression (-match) used in this line.

It might be a good idea to limit the $PathList to Office only...  I got around the error by adding a line $installReg = $installReg.Replace('+', '\)')
But this only solves the issue for folders with a + in the name...  There might be other foldernames that could cause the exact same issue...

**Comment by v-rusmit** [comment]
We believe we have resolved this issue.  Instead of trying to escape every character that may cause an issue we have put a try catch around the -match so any match issue will not cause a failure.  Thank you for feedback!
