### ISSUE TITLE
Scripts are not detecting existing Office configurations and replacing with Office 2016 Applications

### ISSUE THREAD

**Issue by fduarte-msft** [OfficeDev/Office-IT-Pro-Deployment-Scripts#114]
I synced the scripts to the latest versions and performed the following test:
  Installed Office 2010 excluding OneNote and Publisher 2010. I expected the script to replace the existing configuration with Office 2016 configuration. This did not happen and I ended with a full Office 2016 configuration.

**Comment by v-rusmit** [comment]
Thank you for your feedback. We have updated the scripts and have resolved the issue that you describe.
