### ISSUE TITLE
Incorrect Office language for Kazakh

### ISSUE THREAD

**Issue by TOKN2** [OfficeDev/Office-IT-Pro-Deployment-Scripts#115]
In "https://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html" you can choose language for Kazakh that add value: Language ID="kk-kh" ,but this is incorrect. With this configuration installation will fail. 
Correct: Language ID="kk-kz" 

More information:
https://technet.microsoft.com/en-us/library/cc179219.aspx

Thanks! :)

**Comment by v-rusmit** [comment]
We have updated the language ID for Kazakh.  Thank you for pointing our this issue.
