### ISSUE TITLE
Download-OfficeProPlusChannels does not allow to download DC 'extended' builds

### ISSUE THREAD

**Issue by pretzer** [OfficeDev/Office-IT-Pro-Deployment-Scripts#118]
Right now the script does not provide any option to download the latest DC 'extended' build, e.g. Version 1509 (Build 6001.1082), without explicitly referencing the exact version number you want. 
It would be nice if there was some creative way to automatically determine the latest 'extended' build number built into the script. That way you wouldn't have to search for the build number manually on TechNet, which will only be published there on the day the build is released. Thank you!

**Comment by v-rusmit** [comment]
This is something we will look into.  Currently I think the challenge is how do you determine the version of the extended version.

**Comment by v-rusmit** [comment]
Currently there is now way to dynamically detect the extended version.  However this is something that may be available in the near future.  Once that information is available we will update the scripts.
