### ISSUE TITLE
Generate-ODTConfigurationXml on System with O365HomePremRetail

### ISSUE THREAD

**Issue by netraser** [OfficeDev/Office-IT-Pro-Deployment-Scripts#126]
Generate-ODTConfigurationXml on System with O365HomePremRetail installed adds O365ProPlusRetail in the config.xml 
Only one O365 Office is allowed

**Comment by AStigall** [comment]
@netraser we've located the issue causing multiple O365 products being added to the configuration file and will be pushing the fix shortly. Thank you for letting us know about the issue.
