### ISSUE TITLE
Remove-PreviousOfficeInstalls script not detecting 2016 msi installation for removal.

### ISSUE THREAD

**Issue by csmallmda** [OfficeDev/Office-IT-Pro-Deployment-Scripts#141]
The separate Get-OfficeVersion script detects the installation of 2016 msi (not click to run).

Running the Remove-PreviousOfficeInstalls script doesn't appear to detect 2016 msi installation for removal and just seems to do nothing.

`PS C:\Deferred> . .\Get-OfficeVersion.ps1
PS C:\Deferred> Get-OfficeVersion

ComputerName             : COMPUTER-NAME
InstallPath              : C:\Program Files (x86)\Microsoft Office\
ClientCulture            :
Bitness                  : 32-Bit
DisplayName              : Microsoft Office Professional Plus 2016
ClickToRunUpdateUrl      :
Version                  : 16.0.4266.1001
ClickToRunUpdatesEnabled :
ClickToRun               : False

PS C:\Deferred> .\Remove-PreviousOfficeInstalls.ps1
Detecting Office installs...
PS C:\Deferred>`

I appreciate your quick efforts in previous issues that I have brought up with these scripts. I look forward to you being able to get this one resolved as well.

Thanks!

**Comment by csmallmda** [comment]
I tried the most current scripts just now and it still doesn't detect/remove 2016.

Running the Get-OfficeVersion script separately detects the office 2016 installation. But running the Remove-PreviousOfficeInstalls doesn't seem to see the installation and just does nothing when executed.

**Comment by AStigall** [comment]
@csmallmda to remove versions of Office 2016 using the Remove-PreviousOfficeInstalls.ps1 script please be sure to dot source the script...

example: . .\Remove-PreviousOfficeInstalls.ps1. 

Then, run the script using the -Remove2016Installs parameter 

example: Remove-PreviousOfficeInstalls -Remove2016Installs $true.

**Comment by zyzop** [comment]
Hello,
same problem here. 
Script automatically removes 2007 and 2013 versions, but not 2016. Why?


```
PS C:\Users\BarinovK\Desktop\v2> . .\Remove-PreviousOfficeInstalls.ps1
PS C:\Users\BarinovK\Desktop\v2> Get-OfficeVersion

DisplayName                             Version        ComputerName
-----------                             -------        ------------
Microsoft Office Professional Plus 2016 16.0.4266.1001 RU-NAB-IT-PC99


PS C:\Users\BarinovK\Desktop\v2> Remove-PreviousOfficeInstalls
Detecting Office installs...
PS C:\Users\BarinovK\Desktop\v2>
```

**Comment by AStigall** [comment]
@zyzop Remove-PreviousOfficeInstalls is designed to remove any version of Office prior to 2016 when it's ran without any additional parameters. If you want to remove Office, including 2016 versions, you will need to add "-Remove2016Installs $true".

For example, you can run .\Remove-PreviousOfficeInstalls.ps1 -Remove2016Installs $true.

**Comment by zyzop** [comment]
@AStigall Thank you. So just to be sure - for example I have Visio 2007 and Office 2016 installed. Commands to remove all that in one step will be
```
. .\Remove-PreviousOfficeInstalls.ps1
Remove-PreviousOfficeInstalls -Remove2016Installs $true
```
Correct?

**Comment by AStigall** [comment]
@zyzop Yes, if you have the MSI version of 2016 installed. If you have the Click-To-Run version of Office 2016 you would need to type:

`.\Remove-PreviousOfficeInstalls.ps1 -RemoveClickToRunVersions $true -Remove2016Installs $true`
