### ISSUE TITLE
Using these scripts via SCCM doesn't install all of the fonts

### ISSUE THREAD

**Issue by csmallmda** [OfficeDev/Office-IT-Pro-Deployment-Scripts#144]
See this thread on TechNet: [Thread](https://social.technet.microsoft.com/Forums/en-US/8c5ab1dd-fe29-4024-830e-5056ff5ee1d8/office-2016-proplus-the-removal-of-office-2010-and-fonts?forum=Office2016ITPro)

Basically the issue is this:

After running the vb script for 2010 the fonts are removed. (I am focused on Arial Narrow but there are many)

Manually uninstalling Office 2010 via Programs and Features does not remove the fonts, they stay in place.

After 2016 CTR was installed via SCCM with the github deployment scripts, the fonts were not installed.

After 2016 MSI was installed, the Arial Narrow font was installed.

After 2016 CTR was installed manually with the same exact source as the SCCM application, the fonts were installed.

The problem must be between the removal of 2010 via the vb script and the installation of 2016 CTR via the github powershell scripts or something to do with the fact that it is SCCM deploying the software.

**Comment by johnskydiver** [comment]
Hello,
I am currently researching this issue.  I have a couple of questions that will help me further troubleshoot, what I'd like to know is which OS you are deploying to via SCCM, and after the install of Office CTR 2016, does "arial narrow" show up under the font pack "arial" in the path "C:\Windows\Fonts"

Thanks

**Comment by csmallmda** [comment]
This is being deployed to Windows 7 machines. in most scenarios it is removing Office 2010 and installing 2016 CTR.

I have since created a work around. I installed Windows 7 on a VM and then installed Office 2010. I noted the diff in fonts between a clean Windows 7 install and then with 2010 installed.

I then removed 2010 using the provided script Remove-PreviousOfficeInstalls which calls the vb script and removes 2010. This script also removes all of the fonts that Office 2010 put on the system. If you manually uninstall Office 2010 via programs and features, it leaves the fonts in place.

I then noted the diff in fonts between when Office 2010 was installed and now that it had been removed. I packaged up that diff in fonts into a folder, created another powershell script that silently installs all of the fonts in that folder after 2016 CTR finishes its installation. I also pushed just the fonts to all the machines that had previously installed 2016 CTR before I discovered this issue.

This workaround is OK but not ideal. I'm sorry I do not recall if arial narrow showed up under the font family. I do not have a machine handy where I can replicate the issue now.

This only seems to be an issue when I install via SCCM using the various powershell scripts here. I can't even begin to understand why the fonts do not install when Office 2016 installation completes successfully.

**Comment by johnskydiver** [comment]
Thank you for providing detailed information.  After troubleshooting this issue, I was able to replicate the issue.  It turns out that after using the Remove-PreviousOfficeInstalls script, that a reboot is necessary before any of the Office C2R scripts will run correctly and install the missing fonts.  If you want to add a reboot as part of the SCCM deployment script there is a powershell command that will run a reboot.  I can post more details on that when I find it.

Thanks.

**Comment by csmallmda** [comment]
@johnskydiver Thanks. Can you show me how a reboot could be issued by deploying via software center in sccm and then resume with the c2r install after the user logs back in? I'm unaware of how to accomplish that.
