### ISSUE TITLE
Using the Install Toolkit with an existing configuration.xml strips out additional Product IDs

### ISSUE THREAD

**Issue by aaronparker** [OfficeDev/Office-IT-Pro-Deployment-Scripts#148]
The Install Toolkit doesn't provide a way to add additional Product IDs and importing an existing configuration.xml with more than one Product ID (e.g. Office 365 Business + Skype for Business) strips out the additional product IDs.

See the example below where Skype is stripped out by the Install Toolkit:

`<Configuration>
    <Add OfficeClientEdition="32" Channel="Deferred">
        <Product ID="O365BusinessRetail">
            <Language ID="en-us"/>
            <ExcludeApp ID="OneDrive"/>
            <ExcludeApp ID="Groove"/>
            <ExcludeApp ID="Access"/>
        </Product>
        <Product ID="SkypeforBusinessRetail">
            <Language ID="en-us" />
        </Product>
    </Add>
    <Display Level="None" AcceptEULA="TRUE"/>
    <Logging Level="Standard" Path="C:\Windows\Temp"/>
    <Updates Enabled="TRUE" Channel="Deferred"/>
</Configuration>`

**Comment by johnskydiver** [comment]
@aaronparker After reading this post and doing some testing, I can tell you that the toolkit is not stripping all additional product id's.  basically what's going on is that if you have an ID for a product that doesn't exist in the toolkit, then that particular ID cannot be added to the toolkit.  However, I have recently added skype for business and skype for business basic to the toolkit, and a new version of the toolkit with those products included will be available for download by the end of this week.  Thank you for your feedback.
