### ISSUE TITLE
Generate wrapper for 32bit Office, but install 64bit !?

### ISSUE THREAD

**Issue by FUsIon80** [OfficeDev/Office-IT-Pro-Deployment-Scripts#150]
My configuration out of the toolkit:

` <Configuration>
  <Add OfficeClientEdition="32" Channel="Current">
    <Product ID="O365ProPlusRetail">
      <Language ID="de-de" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Project" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Visio" />
      <ExcludeApp ID="OneDrive" />
    </Product>
  </Add>
  <Updates Enabled="FALSE" Channel="Current" />
  <Display Level="Full" AcceptEULA="True" />
  <Property Name="PinIconsToTaskbar" Value="FALSE" />
  <Property Name="AUTOACTIVATE" Value="1" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
  <Property Name="SharedComputerLicensing" Value="0" />
  <Logging Level="Standard" Path="%temp%" />
</Configuration>`

If I create the exe wrapper, this installed the 64bit version of office -.-

I´m working on Win Server 2012 R2 Standard 64bit.

**Comment by johnskydiver** [comment]
Thank you for your feedback.  I tried reproducing the issue stated here, and was unable to, including using the same OS you stated in this thread.  Please insure that you're using the latest version of the toolkit as we've recently updated it.

Thanks.
