### ISSUE TITLE
SharedFunctions.ps1 issues

### ISSUE THREAD

**Issue by daltskin** [OfficeDev/Office-IT-Pro-Deployment-Scripts#152]
There are some illegal characters in this script Lines 331, 1161, 1456,

Also error on Line 331:
    $defaultDisplayPropertySet = New-Object System.Management.Automation.PSPropertySet(�DefaultDisplayPropertySet�,[string[]]$defaultDisplaySet

And issue on line 1454:
If (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(`
    [Security.Principal.WindowsBuiltInRole] Administrator))

**Comment by AStigall** [comment]
Thank you for the feedback. The issues have been corrected and will be updated shortly.
