### ISSUE TITLE
get-officeversion returns nothing

### ISSUE THREAD

**Issue by oogaboogah27** [OfficeDev/Office-IT-Pro-Deployment-Scripts#154]
I've read the readme and checked all the examples.  

Running as admin results in exactly no results:

PS C:\Scripts> . .\Get-OfficeVersion.ps1

PS C:\Scripts> 

Running against a valid computer name results in nothing:

PS C:\Scripts> . .\Get-OfficeVersion.ps1 -ComputerName molsen-vm

PS C:\Scripts> 

I'd love to know what I'm doing wrong.

Downloaded from git today.

**Comment by AStigall** [comment]
@oogaboogah27 After you dot source the script run the function using the ComputerName parameter (do not include the preceding ". .\").

example: Get-OfficeVersion -ComputerName molsen-vm

**Comment by oogaboogah27** [comment]
Got it. My bad. I was expecting to just run the script not call the function. Apologies.

**Comment by AStigall** [comment]
Not a problem! Thank you for reaching out.
