### ISSUE TITLE
10-ExampleRemovePreviousAndUpgradeSCCM.ps1 defines incorrect channel

### ISSUE THREAD

**Issue by davguent** [OfficeDev/Office-IT-Pro-Deployment-Scripts#162]
Deploying 10-ExampleRemovePreviousAndUpgradeSCCM.ps1 using SCCM 1606 to deploy C2R.  I have 'Deferred' element specified within script and on 1st run, it correctly creates configuration.xml with desired settings.  For testing or due to reactive issue, if I uninstall Office 365 ProPlus and rerun install, the temp files from previous run reside in the C:\windows\temp directory and on second run incorrectly sets the channel to ''Current".

Perhaps there is a reason why we shouldn't detect and delete presence of existing configuration.xml in temp directory?

Command in script
Generate-ODTConfigurationXml -Languages AllInUseLanguages -TargetFilePath $targetFilePath | Set-ODTAdd -Version $NULL -SourcePath $SourcePath -Channel Deferred | Set-ODTDisplay -Level Full -AcceptEULA $true | Set-ODTProductToAdd -ProductId "O365ProPlusRetail" -ExcludeApps ("Groove", "OneDrive") | Out-Null

[configuration.zip](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/files/477329/configuration.zip)

**Comment by AStigall** [comment]
We fixed the bug that was setting an incorrect variable for $Channel if the Channel was specified when running Set-ODTAdd. 

Thank you for your feedback!

**Comment by AStigall** [comment]
Reopening until fix is merged into master

**Comment by shgass** [comment]
test

**Comment by davguent** [comment]
Verified latest drop on GitHub resolved issue. Thank you.
