### ISSUE TITLE
Update-Office365Anywhere only checking XML based update registry path

### ISSUE THREAD

**Issue by pretzer** [OfficeDev/Office-IT-Pro-Deployment-Scripts#166]
For the primary update location the script currently only checks the registry keys which are set by defining them in the installation **XML** file:
- Office 2016: HKLM\Software\Microsoft\Office\ClickToRun\Configuration!UpdateUrl
- Office 2013: HKLM\Software\Microsoft\Office\15.0\ClickToRun\Configuration!UpdateUrl

Customers also have the option to define the update location via **GPO** though, which are written to a different location in the registry:
- Office 2016: HKLM\Software\Policies\Microsoft\Office\16.0\Common\OfficeUpdate!UpdatePath
- Office 2013: HKLM\Software\Policies\Microsoft\Office\15.0\Common\OfficeUpdate!UpdatePath

The Office update engine takes the both paths into account, in fact prioritizing the path set by GPO over the path set by the XML (**GPO path > XML path**). The script however only checks the XML path at the moment. I'd suggest adding checks for the GPO paths with the same kind of prioritizing logic (GPO > XML). Thanks!

**Comment by AStigall** [comment]
@pretzer it looks like we are already looking for the UpdatePath GPO before defining the UpdateSource. If you take a look at the Update-Office365Anywhere.ps1 [script](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/blob/master/Office-ProPlus-Updates/Update-Office365Anywhere/Update-Office365Anywhere.ps1) at line 1114 we start to look for the GPOs.  At line 1120 we look for the GPO path and if it doesn't exist we look for the UpdateUrl in the Configuration path.

We aren't looking for 2013 locations though so we might consider adding those. 

Let me know if you don't see the same.
