### ISSUE TITLE
Update-Office365Anywhere error handling improvements

### ISSUE THREAD

**Issue by pretzer** [OfficeDev/Office-IT-Pro-Deployment-Scripts#167]
Hi, 
I've received similar feedback from two customers regarding the script Update-Office365Anywhere around how errors are handled/returned:
- Is it possible to add actual return codes to the script if it fails? At the moment it always returns 0.
- Can we add better explanations why a failure occurs? For example, when you call with the script with these parameters **-EnableUpdateAnywhere $false -UpdateToVersion 16.0.6741.2071** and this particular version is not available in the primary update source, it should output/log that it "didn't find the version in the update source"
  Thanks!

**Comment by AStigall** [comment]
@pretzer we are working on a more advanced solution to improve error handling for all of the scripts. Identifying milestones like you provided in your example is very helpful for us.

**Comment by johnskydiver** [comment]
Logging and error logging added to scripts
