### ISSUE TITLE
Update-Office365Anywhere Channel Detection

### ISSUE THREAD

**Issue by zakgodwin** [OfficeDev/Office-IT-Pro-Deployment-Scripts#168]
This isn't so much an issue more so a question regarding the Update-Office365Anywhere script. It was my understanding that the script had the ability to determine what channel the client was running then build the correct channel share path. Working my way through this script in testing, it finds a channel folder but not the correct channel that is installed.

Edit: After additional research, I see that Change-UpdatePathToChannel calls Detect-Channel and returns the value found. I know on this test box that it has the June 6th Current Channel build installed. However, Detect-Channel is returning Deferred as the channel found.

Edit: The CDNBaseUrl is set to the address of the Deferred Channel, this install started as Deferred channel then updated to Current channel using c2rclient.exe. I would assume that it would update the CDNBaseUrl though. Looking at the StreamPackageUrl values these show the correct address that would match for Current Channel.

**Comment by AStigall** [comment]
You're definitely on the right path here. Detect-Channel looks for the value of CDNBaseUrl and matches that with the url for the channels defined in the xml files inside of the ofl.cab file.

Is this the switch you used to change from Deferred to Currnet?

OfficeC2RClient.exe /changesetting Channel=<channelName>

**Comment by zakgodwin** [comment]
I believe I used the updatetoversion switch. I modified the code to give preference to the streampackageurl registry value on a condition of the cdnbaseurl registry value. I'll post the code when I get a chance.

**Comment by AStigall** [comment]
@zakgodwin we are testing a fix for this that will incorporate a new system to detect the existing channel. Thank you for bringing this to our attention. I'll post again when we're done testing and have pushed the fix.

**Comment by AStigall** [comment]
@zakgodwin The new method to detect channels has been pushed. Below is the order of priority:

UpdateChannel > UpdatePath (GPO) > UpdateBranch (GPO) > UpdateChannel (GPO) > UpdateUrl > CDNBaseUrl

Let us know if you still see issues.

**Comment by AStigall** [comment]
Scripts have been updated with better channel detection.
