### ISSUE TITLE
Generate-ODTConfigurationXML failure with Multiple Office products installed.

### ISSUE THREAD

**Issue by BGleasonGH** [OfficeDev/Office-IT-Pro-Deployment-Scripts#171]
Same issue as here:
https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/issues/158

The user just appears to never respond..

I am getting this failure as well... Mine was:
You cannot call a method on a null-valued expression.
At C:\Users<Username>\Desktop\Office-ProPlus-Deployment\Deploy-OfficeClickToRun
\Generate-ODTConfigurationXML.ps1:1311 char:54

$OfficeVersion = $OfficeVersion.Version.Split <<<< (".")[0]
CategoryInfo : InvalidOperation: (Split:String) [], ParentConta insErrorRecordException
FullyQualifiedErrorId : InvokeMethodOnNull

I went as far to see the data in $OfficeVersion and it returned this (mind you all compact)...:
@{ComputerName=WIN7X64;
InstallPath=C:\Program Files (x86)\Microsoft Office\;
ClientCulture=;
Bitness=32-Bit;
DisplayName=Microsoft Office Professional Plus 2007;
ClickToRunUpdateUrl=;
Version=12.0.6612.1000;
ClickToRunUpdatesEnabled=;
ClickToRun=False}

@{ComputerName=WIN7X64;
InstallPath=C:\Program Files (x86)\Microsoft Office\;
ClientCulture=;
Bitness=32-Bit;
DisplayName=Microsoft Office Visio Standard 2007;
ClickToRunUpdateUrl=;
Version=12.0.6425.1000;
ClickToRunUpdatesEnabled=;
ClickToRun=False}

@{ComputerName=WIN7X64;
InstallPath=C:\Program Files (x86)\Microsoft Office\;
ClientCulture=;
Bitness=32-Bit;
DisplayName=Microsoft Office Project Standard 2010;
ClickToRunUpdateUrl=;
Version=14.0.6029.1000;
ClickToRunUpdatesEnabled=;
ClickToRun=False}

So looks like get-officeversion is returning too much information/all office apps installed... Just prelim..

**Comment by johnskydiver** [comment]
This issue has been resolved
