### ISSUE TITLE
offscrubc2r.vbs not removing old shortcuts

### ISSUE THREAD

**Issue by greenrock2** [OfficeDev/Office-IT-Pro-Deployment-Scripts#172]
The software shortcuts created by users are not deleted by default by offscrubc2r.vbs. I have to execute a script to remove shortcuts from desktop, taskbar and start menu. example 

Function UnPinFromTaskBar(strFFilePath)
    strFolder = objFSO.GetParentFolderName(strFFilePath)
    strFile = objFSO.GetFileName(strFFilePath)  

```
If objFSO.FileExists(strFFilePath) Then
    Set objFolder = objShell.Namespace(strFolder)
    Set objFolderItem = objFolder.ParseName(strFile)
    Set colVerbs = objFolderItem.Verbs
```

'       MsgBox objverb
        For Each objVerb in colVerbs
            If Replace(objVerb.name, "&", "") = "Détacher de la barre des tâches" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "Désépingler de la barre des tâches" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "Unpin from Taskbar" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "von taskleiste lösen" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "desanclar de la barra de tareas" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "odepnout z hlavního panelu" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "frigør fra proceslinje" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "van de taakbalk losmaken" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "poista kiinnitys tehtäväpalkista" Then objVerb.DoIt
            If Replace(objVerb.name, "&", "") = "rimuovi dalla barra delle applicazioni" Then objVerb.DoIt
        Next
    End If
End Function

**Comment by AStigall** [comment]
@greenrock2 thank you for sending this to us. We've actually been working on a new function that will pin/unpin Office applications to/from the Start Menu/Taskbar. 

Do you see this issue with any specific operating system or build?

**Comment by greenrock2** [comment]
I see this issue on windows 7 enterprise computers. Experience given during the pilote phasis of uninstallation of hundreds of Office C2R 2013 in order to install office C2R 2016 instead. I had to use vbscript and batch in order to do the job.

**Comment by johnskydiver** [comment]
Tested new scripts on a few scenarios, they work just fine now.
