### ISSUE TITLE
Wix compiler/linker cannot be found

### ISSUE THREAD

**Issue by ciphertxt** [OfficeDev/Office-IT-Pro-Deployment-Scripts#174]
When attempting to create the Install Wrapper in the [Install Toolkit](https://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html) the generator is unable to find the Wix compiler and generates the error: 

> Wix compiler/linker cannot be found

OS: Windows 10 Pro (Version 1607 Build 14393.321)

<img width="769" alt="2016-10-24 10_01_17-" src="https://cloud.githubusercontent.com/assets/3347244/19648745/2937e07a-99d1-11e6-8b3e-1994c56775fb.png">

**Comment by alex182** [comment]
@ciphertxt I am investigating this issue.  I was able to reproduce this error by deleting either/both the candle.exe/light.exe from the %temp%\wixTools directory.  Are either of those executables missing on your workstation?

**Comment by ciphertxt** [comment]
They are. I have the wixTools folder at **%temp%\wixTools** but the folder and all of the subfolders under **\sdk\** are empty.

**Comment by alex182** [comment]
@ciphertxt please try deleting the entire %temp%\wixTools folder and then re-install the toolkit

**Comment by ciphertxt** [comment]
That did it. Thanks @alex182!
