### ISSUE TITLE
Deploy as Startup script through GPO?

### ISSUE THREAD

**Issue by techronaut** [OfficeDev/Office-IT-Pro-Deployment-Scripts#176]
Having a hard time finding the intended deployment method for the "10-RemovePreviousandUpgrade.ps1" deployment script. It does work when run manually. Are these intended to be startup scripts? Thanks.

**Comment by AStigall** [comment]
Hi @techronaut,

The deployment method is really up to your discretion. You can deploy the script through a GPO, using software distribution such as System Center Configuration Manager or Intune, or by running them manually.
