### ISSUE TITLE
Invalid Source Files when trying to embed into exe

### ISSUE THREAD

**Issue by keane2017** [OfficeDev/Office-IT-Pro-Deployment-Scripts#177]
When trying to embed the downloaded source files (from the download section)
I am constantly receiving invalid source files, they are over 1 gb in size and the path is correct?
can you advise please
![office1](https://cloud.githubusercontent.com/assets/23102516/19773285/e0b7d318-9c60-11e6-93ed-792732526c63.JPG)
![office2](https://cloud.githubusercontent.com/assets/23102516/19773286/e0b86706-9c60-11e6-86af-ca689cba2a9c.JPG)

can someone advise where I am going wrong with this please?
Thanks

**Comment by johnskydiver** [comment]
@keane2017 I was unable to reproduce this error.  It's possible that one of the downloaded files may have been corrupted.  Please delete the directory you downloaded the files to, and use the download tab of the toolkit to re-download the content.  If this results in another error, please post the path you use on the download tab, and the path you used on the generate tab for the source file path so we can confirm both paths are valid.  I hope this helps.

**Comment by keane2017** [comment]
Good evening
It's when I try to use the current version rather than deferred I still get the issue.
Can you confirm which you used?
Thanks

**Comment by johnskydiver** [comment]
@keane2017 I can confirm that I am using the current version, and even the same version number as it appears in your screenshot.

**Comment by keane2017** [comment]
all sorted
third time round it worked :)
