### ISSUE TITLE
MSI Install of Office

### ISSUE THREAD

**Issue by keane2017** [OfficeDev/Office-IT-Pro-Deployment-Scripts#178]
HI
i have installed the MSI i have generated for office proplus 365
But office doesnt install?

can someone explain how it works for a newbie please? does it extract the files to c:\Program Files\ and then run something else?

If i Generate the exe is it any different in how it works? 

I dont want an MSI generating a successful install if its still busy in the background doing something as users will complain?

i have embedded the office files in the installer and its over 1.7 gb in size

Thanks 
Chris

**Comment by johnskydiver** [comment]
It will work, if you embed the files, the files have to be copied to c:\windows\temp\OfficeProPlus first.  The reason it seems to be hanging is because you embedded the files.  Most computers take a few minutes to load and complete the processes of a 2GB file.  Please be patient.
