### ISSUE TITLE
Line number 0 error - generating office msi

### ISSUE THREAD

**Issue by keane2017** [OfficeDev/Office-IT-Pro-Deployment-Scripts#179]
Hi
I am trying to generate an office msi this morning
but whenever I click generate I am seeing the error in the screenshot below
![office3](https://cloud.githubusercontent.com/assets/23102516/19836751/0aa8a6aa-9ea2-11e6-978c-317d0d98aac2.JPG)

Can anyone advise? I have tried a new folder for the source and the output but get the same error?
Thanks

**Comment by keane2017** [comment]
i have tried this again today on a fresh machine and get the same error?
has anyone else seen this?

**Comment by Adam-Driver** [comment]
Same issue, is there an older version of the tool available?

**Comment by johnskydiver** [comment]
@keane2017 @Adam-Driver Thanks for bringing the issue to our attention.  We are currently looking into it.  No, there is not an older version of the toolkit available.  Thanks.

**Comment by TurboGFF** [comment]
I'm also getting this problem. I've tried downloading/creating MSI file on two different machines, and they both fail with the above.

**Comment by keane2017** [comment]
Good afternoon
is there any update on this please?
Thank you

**Comment by johnskydiver** [comment]
We're still looking into it, we'll let you know as soon as we have an update.  Thanks.

**Comment by johnskydiver** [comment]
The issue has been resolved and is available from the latest build of the toolkit.  Thank you for your patience.

**Comment by keane2017** [comment]
Hi
it may have been resolved but now the option to add skype is missing? a lot of the options like logging etc are now missing?
can you advise if this is coming back please?
Thank you

**Comment by johnskydiver** [comment]
Those features will be returning shortly.  Thanks.

**Comment by keane2017** [comment]
Okay thank you I shall wait for them to
Be available as I need Skype in my office Install :)

**Comment by TurboGFF** [comment]
Trying out the new build of the toolkit, and I've reached this point.

As you can see, I've selected MSI as the file type and at some point, the msi file does appear, but then it gets replaced by the .exe and a bunch of other files.   Do you know how long this step is supposed to take? According to the toolkit, it's still working at something.

![image](https://cloud.githubusercontent.com/assets/23172492/19932197/8f1874d4-a0e5-11e6-81a4-60ebcdcf0ab8.png)

**Comment by keane2017** [comment]
I have managed to build 3 msi,s today
If you embed the files it takes over an hour to complete

**Comment by johnskydiver** [comment]
@TurboGFF since you chose to imbed the source files, it's going to take a while.  The exe file it's trying to put into an MSI is nearly 2 GB.  If you don't imbed the source files, it goes much quicker.  the amount of time it takes varies from machine to machine.  On my machine, it takes roughly 25 minutes.

**Comment by TurboGFF** [comment]
Over an hour, wow. I hope it doesn't take that long to install them ;)   Only reason I'm embedding the files is because I figure it would be faster to install office over the local network than to grab them from the internet when deploying through MDT.

**Comment by keane2017** [comment]
@johnskydiver do you have any eta on when Skype will be available again please?

**Comment by keane2017** [comment]
Maybe a slight exaggeration but it's week
Over 30 mins. Works good when it's complete though. Handy tool :)

**Comment by johnskydiver** [comment]
new update of toolkit is available.  The additional options have been put back in.  Thanks everyone for your patience.

**Comment by johnskydiver** [comment]
closing as issue has been resolved
