### ISSUE TITLE
Non silent install silent when using tool

### ISSUE THREAD

**Issue by keane2017** [OfficeDev/Office-IT-Pro-Deployment-Scripts#181]
Good evening
I have created an msi using the tool
I have selected a non silent install but when I install the msi everything is done in the background? I also selected full display Eula

Can you advise what I am
Doing wrong as I really need the office splash screens available due to how it's deployed.

Can the msi be deployed like this? Or do I need to create an exe instead? With the files embedded?
Thank you

**Comment by johnskydiver** [comment]
@keane2017 you can check the configuration xml in the path c:\windows\temp\officeproplus  have a look at the configuration xml, The display level should be set to "full" for a non-silent install.  if it says "none" then you set one of the flags in the toolkit incorrectly.

**Comment by keane2017** [comment]
Hi please see below
that's the steps I followed
as you will see its not populating the config file properly in the tool when you generate the MSI
![problem1](https://cloud.githubusercontent.com/assets/23102516/19946518/45d067ee-a13c-11e6-9d92-df6b04b04550.JPG)
![problem2](https://cloud.githubusercontent.com/assets/23102516/19946515/45cce7cc-a13c-11e6-84c3-600ec7ebba9b.JPG)
![problem3](https://cloud.githubusercontent.com/assets/23102516/19946519/45d16ed2-a13c-11e6-9a8b-1b02da36121b.JPG)
![problem4](https://cloud.githubusercontent.com/assets/23102516/19946517/45ce2722-a13c-11e6-89a5-44ba7038b93c.JPG)
![problem5](https://cloud.githubusercontent.com/assets/23102516/19946516/45cdbdaa-a13c-11e6-9b39-f717af8786eb.JPG)
![problem6](https://cloud.githubusercontent.com/assets/23102516/19946520/45d3143a-a13c-11e6-8640-25e570b0c5c8.JPG)
![problem7](https://cloud.githubusercontent.com/assets/23102516/19946524/45ebeb0e-a13c-11e6-9c60-f5dc9a0a9fce.JPG)
![problem8](https://cloud.githubusercontent.com/assets/23102516/19946525/45ed732a-a13c-11e6-9e65-075f7c8ea378.JPG)
![problem9](https://cloud.githubusercontent.com/assets/23102516/19946522/45e75ba2-a13c-11e6-8686-a51be4a312f7.JPG)
![problem10](https://cloud.githubusercontent.com/assets/23102516/19946523/45eaf28a-a13c-11e6-9de8-e01566653a71.JPG)

What option should I be changing as I appear to have it all set correctly ?

Thanks
Chris

**Comment by johnskydiver** [comment]
before you click generate, double check the configuration on the "configuration" tab of the generate page.  If display level shows "none" then toggle it, and check again.
