### ISSUE TITLE
Please save / put .ps1 files as 'UTF-8 with BOM' encoding instead of ANSI ecoding

### ISSUE THREAD

**Issue by sho5aki** [OfficeDev/Office-IT-Pro-Deployment-Scripts#183]
Maybe this issue will reproduce on non-English Windows enviroment.
For example, when I will run Office-ProPlus-Preparation\Check-OfficeProPlusPorts\Check-OfficeProPlusPorts.ps1, I will see the following errors (display in Japanese because my enviroment is Japanese):

PS C:\work\Office-IT-Pro-Deployment-Scripts\Office-ProPlus-Preparation\Check-OfficeProPlusPorts> .\Check-OfficeProPlusPorts.ps1
船efaultDisplayPropertySet・[string[]]$defaultDisplaySet : 用語 '船efaultDispla
yPropertySet・[string[]]$defaultDisplaySet' は、コマンドレット、関数、スクリプ
ト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく
記述されていることを確認し、パスが含まれている場合はそのパスが正しいことを確認
してから、再試行してください。
発生場所 C:\work\Office-IT-Pro-Deployment-Scripts\Office-ProPlus-Preparation\Ch
eck-OfficeProPlusPorts\Check-OfficeProPlusPorts.ps1:32 文字:88
+ ... PSPropertySet(船efaultDisplayPropertySet・[string[]]$defaultDisplaySet)
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (船efaultDisplayP...faultDisplayS
    et:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

This issue was provided because PowerShell will MISS-translate from ANSI encoding scripts to enviroment specific one (UTF-8 with BOM in this case).
- Original) "New-Object System.Management.Automation.PSPropertySet(**'D**efaultDisplayPropertySet**',**[string[]]$defaultDisplaySet)"
- Translated) "New-Object System.Management.Automation.PSPropertySet(**船**efaultDisplayPropertySet**・**[string[]]$defaultDisplaySet)".

This issue also happen on both Generate-ODTConfigurationXML.ps1 and Get-OfficeVersion.ps1.
Due to avoid this issue, please save any .ps1 files as UTF-8 with BOM encoding and pull to GitHub. My understanding is UTF-8 with BOM is the default one on PowerShell ISE when you will save scripts.

**Comment by johnskydiver** [comment]
Sorry it's taken me so long to respond.  Can you do me a favor and test this script and let me know if it works?
https://valoremconsulting1com-my.sharepoint.com/personal/jojones_valorem_com/_layouts/15/guestaccess.aspx?guestaccesstoken=hASoQLuzcxfnM57wiTlglcEhnhA46cnpOJO%2bdQBjRAo%3d&docid=0753e933323c045f89c49be49f63da600&rev=1
thanks.

**Comment by sho5aki** [comment]
Yes. it's working on my enviroment!

**Comment by alex182** [comment]
@sho5aki 

I converted all of our scripts to UTF-8 in the [Bug-ConvertScriptsToUTF8 branch](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/tree/Bug-ConvertScriptsToUTF8).  I will have to test them extensively before they are merged into the Master branch, but if you'd like to use UTF-8 versions of our scripts that is where they are located.
