### ISSUE TITLE
MSIs not giving correct display property

### ISSUE THREAD

**Issue by keane2017** [OfficeDev/Office-IT-Pro-Deployment-Scripts#185]
Hi
i have recreated the MSI for office visio and project today
when I toggle the display level to FULL it shows up fine in the config before you generate the MSI, when you generate and deploy the MSI the configuration.xml file shows the display_level as none
can you advise why this is happening please?

I have tried 5 times and everyone is the same its not changing it correctly?

Thanks

**Comment by johnskydiver** [comment]
@keane2017 This is unusual behavior that I have never seen before.  Can you please provide me with all the selections you've made on the toolkit before clicking generate?

**Comment by johnskydiver** [comment]
before you begin the install with the MSI, make sure the folder C:\Windows\Temp\OfficeProPlus is empty.  Also make sure that you are running the MSI without any additional arguments.  For example, if you are running the msi with the argument /silent, this will make the install a silent install regardless of what you specified in the toolkit during generation.
