### ISSUE TITLE
Edit-OfficeConfigurationFile.ps1 fails when CDN is not accessible

### ISSUE THREAD

**Issue by davguent** [OfficeDev/Office-IT-Pro-Deployment-Scripts#187]
For scenarios where customers may be performing desktop imaging on internet disconnected environments, there is an expectation that deployment scripts will proceed.  It works with ODT without scripts.  We'd like to have scripts function with internet is not accessible.

Specifically, line 3542 Edit-OfficeConfigurationFile.ps1 

Line 3542

    if ($downloadFile) {
           $webclient = New-Object System.Net.WebClient
           $XMLFilePath = "$env:TEMP/ofl.cab"
           $XMLDownloadURL = "http://officecdn.microsoft.com/pr/wsus/ofl.cab"
           $webclient.DownloadFile($XMLDownloadURL,$XMLFilePath)

           if ($FolderPath) {
             [System.IO.Directory]::CreateDirectory($FolderPath) | Out-Null
             $targetFile = "$FolderPath\ofl.cab"
             Copy-Item -Path $XMLFilePath -Destination $targetFile -Force
           }
       }

**Comment by alex182** [comment]
@davguent that specific function has a parameter called FolderPath which can be used if you have a copy of the ofl.cab file already downloaded.  You just have to set that parameter to the path of the folder that contains the ofl.cab file and the script will extract the correct configuration xml.

For example, say you have the ofl.cab file in the C:\OfficeChannelFiles folder you use the following command:

`Get-ChannelXml -FolderPath C:\OfficeChannelFiles -Bitness 32`
