### ISSUE TITLE
Install-OfficeClickToRun XML handling

### ISSUE THREAD

**Issue by SubThr33** [OfficeDev/Office-IT-Pro-Deployment-Scripts#188]
Hi,

I have been looking into the Install-OfficeClickToRun script and have found some items which feel like issues, I am only relatively new to PowerShell so I could be wrong.

On execution I am passing a previously generated XML file from http://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html using the -ConfigurationXML parameter, the .xmlLoad method seems to be looking for a XML string rather than a file path. Once I tested this with the .load method instead, it seemed to work as intended. Is this by design?

```
if ($TargetFilePath) {
        $ConfigFile.Load($TargetFilePath) | Out-Null
    } else {
        if ($ConfigurationXml) 
        {
>            $ConfigFile.LoadXml($ConfigurationXml) | Out-Null
            $global:saveLastConfigFile = $NULL
            $TargetFilePath = $NULL
        }
    }
```

This issue may well be linked to the one above, but when a XML config file path is passed as the -ConfigurationXML parameter, the configuration.xml file is then overwritten on line 157 with a new Configuration.xml file which contains the parameters path string. E.g. C:\temp\configuration.xml is overwritten and the only file content is "C:\temp\configuration.xml"

```
    if (!($TargetFilePath)) {
      if ($ConfigurationXML) {
         $TargetFilePath = $scriptRoot + "\configuration.xml"
>         New-Item -Path $TargetFilePath -ItemType "File" -Value $ConfigurationXML -Force | Out-Null
      }
    }
```
Thanks!

**Comment by alex182** [comment]
@SubThr33 can you try using the -TargetFilePath parameter with the path to your configuration xml file as the value instead of using the -ConfigurationXML parameter?

**Comment by SubThr33** [comment]
@alex182 Sorry for the delay.

I have just tested the install script using -TargetFilePath instead of -ConfigurationXML and it installs correctly.
Is this one by design?
