### ISSUE TITLE
Downloading issues

### ISSUE THREAD

**Issue by mprentice22153** [OfficeDev/Office-IT-Pro-Deployment-Scripts#196]
I've tried to download the entire project via the zip file multiple times and I'm getting an error that the zip file is invalid.  I've downloaded the GitHub Desktop app and tried to clone the project to my computer.  It also returns a failure.  I'd like to download the project but currently can't.

**Comment by johnskydiver** [comment]
@mprentice22153 Our team is currently working on the repository to make sure it can easily be downloaded via zip and extracted by windows.  In the mean time, you can connect to the code in question with one of a few git programs, or use 7-zip to extract the zipped folder.  7-zip handles it just fine.

Thanks.

**Comment by knickknackpadillac** [comment]
Having the same issue with 7-zip.  Tried downloading the master.zip file twice, but 7-zip is reporting that it's invalid.  Did this every get resolved?
