### ISSUE TITLE
Notepad++ / Get-OfficeVersion 

### ISSUE THREAD

**Issue by ColdFire1985** [OfficeDev/Office-IT-Pro-Deployment-Scripts#198]
Hi there, 

I found an issue if Notepad++ is installed. The Installation/Remove (Get-OfficeVersion Line235) crashes by parsing the Registry in the second foreach (Line 235).

OLD:
```
 foreach ($officeInstallPath in $PathList) {
             if ($officeInstallPath) {
                $installReg = "^" + $installPath.Replace('\', '\\')
                $installReg = $installReg.Replace('(', '\(')
                $installReg = $installReg.Replace(')', '\)')
                if ($officeInstallPath -match $installReg) { $officeProduct = $true }
             }
           }
```

MyFix:
```
 foreach ($officeInstallPath in $PathList) {
             if ($officeInstallPath) {
                $installReg = "^" + $installPath.Replace('\', '\\')
                $installReg = $installReg.Replace('(', '\(')
                $installReg = $installReg.Replace(')', '\)')
                $installReg = $installReg.Replace('+', '\+')
                if ($officeInstallPath -match $installReg) { $officeProduct = $true }
             }
           }

```

The InstallLocation in the Registry was C:\Program Files (x86)\Notepad++

I don´t know if this is a good solution but it works 4 me ;-)

Greetings ColdFire

**Comment by johnskydiver** [comment]
@ColdFire1985 This issue was rectified in a prior script update.  Can you please make sure you have the latest version of the script and let me know if notepad++ still causes the script to crash.  Thanks.

**Comment by ColdFire1985** [comment]
Hi, 

I downloaded the scripts from Git a few days ago.
Problem ist that in this directory: Office-IT-Pro-Deployment-Scripts/Office-ProPlus-Deployment/Deploy-OfficeClickToRun/ where the samples are the fix IMHO is not included.

**Comment by johnskydiver** [comment]
@ColdFire1985 Can you check your regkey, and tell me if you have a value at InstallLocation under the key HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++
If you have a value there, then that will cause a crash.  Every test machine I've run does not, which I find very odd.  In any case, I'll see about adding that adjustment.
Thanks.
John J.

**Comment by ColdFire1985** [comment]
@johnskydiver You are right. The key on a 64bit Windows 10 is exactly what you posted. If you install notepad++ by default settings you will get this uninstall key location. In my test environment it causes the office deploymentscript to crash.

**Comment by johnskydiver** [comment]
@ColdFire1985 After reviewing with my team, we've decided to correct a different way.  We've wrapped the event in a try catch block just in case there are any other programs with illegal characters we haven't been able to see yet.  You can grab the latest from the development branch if you like.  Thank you for your input.
