### ISSUE TITLE
ClickOnce application MSI/EXE source path

### ISSUE THREAD

**Issue by DareDreamer** [OfficeDev/Office-IT-Pro-Deployment-Scripts#199]
Hi,
When creating EXE/MSI installation based using your tool, the installation downloads the Office setup files from the internet. Is there a way the MSI/EXE would look for the "office" folder in the current path? I don't want to specify a "SourcePath" in the XML. I want it to be flexible.
Just asking if this is possible.
Thank you very much.

**Comment by AStigall** [comment]
@DareDreamer If you specify the relative path ".\" in SourcePath it will look for the Office folder where the MSI/EXE is being ran from.

**Comment by AStigall** [comment]
@DareDreamer As of now, you will need to specify a path to the Office folder.
