### ISSUE TITLE
excludeApps

### ISSUE THREAD

**Issue by netraser** [OfficeDev/Office-IT-Pro-Deployment-Scripts#200]
if you use Generate-ODTConfigurationXml and the installed Office has a App Excluded there is no Parameter to Include Apps.
This is an issue to later change the set of excluded applications.

**Comment by AStigall** [comment]
@netraser Thank you for the feedback. We'll discuss a method to implement this solution.

**Comment by AStigall** [comment]
@netraser We have added a new parameter called KeepExcludedApps which is set to $true by default and will capture the existing excluded apps. If this parameter is set to $false all default apps will be included in the configuration.xml file. For example,

Generate-ODTConfigurationXML -TargetFilePath configuration.xml -Languages CurrentOfficeLanguages -KeepExcludedApps $false
