### ISSUE TITLE
Remove-PreviousOfficeInstalls - Undefined Function

### ISSUE THREAD

**Issue by mcmcghee** [OfficeDev/Office-IT-Pro-Deployment-Scripts#202]
On line 106, Remove-PreviousOfficeInstalls.ps1 references an undefined function "Remove-PinnedOfficeApplications" for Windows 10 machines.

https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/blob/master/Office-ProPlus-Deployment/Remove-PreviousOfficeInstalls/Remove-PreviousOfficeInstalls.ps1

**Comment by johnskydiver** [comment]
@mcmcghee The issue has been corrected.
