### ISSUE TITLE
Telemetry Dashboard SQL Script Returns Warning for Key Length

### ISSUE THREAD

**Issue by Kazzan** [OfficeDev/Office-IT-Pro-Deployment-Scripts#203]
Hello, in strictly managed environment, we get warnings when SQL admins prepare database for Office Telemetry. Is this by design or can be fixed?

Warning! The maximum key length is 900 bytes. The index 'IX_BuiltInSolutions_SolutionType_FileName_ProgId' has maximum length of 1034 bytes. For some combination of large values, the insert/update operation will fail.

Warning! The maximum key length is 900 bytes. The index 'CIX_BuiltInSolutions' has maximum length of 1035 bytes. For some combination of large values, the insert/update operation will fail.

**Comment by johnskydiver** [comment]
@Kazzan is this error popping up from trying to setup SQL for telemetry, or does this error pop from one of our scripts.  If it is from trying to setup SQL for telemetry, you will need to contact Premier support for assistance.  https://support.microsoft.com/en-us/premier
Here is some additional info for setting up telemetry dashboard
https://technet.microsoft.com/en-us/library/jj219431.aspx

**Comment by Kazzan** [comment]
It came from SQL script https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/blob/master/Office-ProPlus-Management/Deploy-OfficeTelemetryDashboard/OfficeTelemetryDatabase.sql after we run on SQL 2014 Enterprise.
