### ISSUE TITLE
Office 16 Click-to-Run Extensibility Component 64-bit Registration prevent the installation of office click-to-run 32 bits

### ISSUE THREAD

**Issue by greenrock2** [OfficeDev/Office-IT-Pro-Deployment-Scripts#205]
Office 16 Click-to-Run Extensibility Component 64-bit Registration prevent the installation of office click-to-run 32 bits and is not uninstalled by offscrubc2r.vbs script.
I have to uninstall it by MsiExec.exe /X{90160000-00DD-0000-1000-0000000FF1CE} /qn

Why this product is not uninstalled by offscrubc2r.vbs?

**Comment by manoth-msft** [comment]
Should be fixed in the latest offscrubc2r.vbs (V2.12) which was published about two weeks ago. Plese verify that you're running the latest release.

**Comment by greenrock2** [comment]
Thanks for the answer and the update. Where can we have information about the improvements, new features and bug fixes of your scripts ?

When I go to the direct link to the offscrubc2r.vbs I see a 2.03 scriptversion 
https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/blob/a213174770584ce0e846e30c62eb70f80a04dbe3/Office-ProPlus-Deployment/Remove-PreviousOfficeInstalls/OffScrubc2r.vbs

I have to download all the scripts in https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts
to download the last version of offscrub

**Comment by AStigall** [comment]
Thank you for the feedback. We'll make sure the repositories are updated with the latest release of the offscrub scripts.

**Comment by AStigall** [comment]
The PowerShell scripts have been updated with the latest releases of the Offscrub vbs scripts.

**Comment by kukubau** [comment]
Thank you for these scripts! Great work!

One question though. Does OfficeScrub scripts accept VISSTD and VISPRO switch, and if the case, does it leave the office installation unaltered?

I'm uninstalling Visio 2003, 2007, 2013, 2016 (clickToRun - Std and Pro) remotley and I'm afraid it will break the office installation on users' machines.

Thank you.
