### ISSUE TITLE
MSI creation fails when attempting to embed office installation files

### ISSUE THREAD

**Issue by CThompso3** [OfficeDev/Office-IT-Pro-Deployment-Scripts#206]
I'm a little stumped. I created an MSI with embedded files with no problem yesterday; however, today it fails with the message "**Error Cannot find office files**". Configuration.xml and installation files have been saved at *C:\temp\office365*. I've deleted and re-downloaded the installation files just to be sure. I've tried using the toolkit by importing my existing configuration.xml file and starting from scratch to no avail. I've also tried moving the configuration and installation files to a different location but get the same results. I have uninstalled and re-installed the toolkit with no change. I get to the end and I see this every time:

![screenshot 48](https://cloud.githubusercontent.com/assets/26146315/23518658/cd1e79e2-ff39-11e6-9795-5481723c9ef4.jpg)

Some additional details regarding this configuration:
1. **Product:** Office 365 for Business
1. **Edition:** 64-bit
1. **Channel:** Current
1. **No Exclusions**
1. **Updates:** Enabled for *Current* channel
1. **Options:**
    1. **Display Level:** None
    1. **Accept EULA:** True
    1. **Auto Activate:** Yes
    1. **Force App Shutdown:** True
    1. **Shared Computer Licensing:** False
    1. **Pin Icons:** False
    1. **Enable Config Manager:**: True

As a note: While playing around with this I decided I didn't want to embed the files in the MSI (so long as everything installs from the source folder, allowing me to update the source files as needed), but I'll be more than happy to test some things and provide any additional information if needed.

**Comment by AStigall** [comment]
@CThompso3 Thank you for the detailed description of your issue. We are working on this.

**Comment by johnskydiver** [comment]
@CThompso3 Please tell me the folder hierarchy of what's in C:\temp\office365

Thanks.

**Comment by CThompso3** [comment]
C:\temp\office365 contained *setup.exe* and *configuration.xml*. Office files were downloaded using *setup.exe /download configuration.xml* which created a folder named *Office* with the required installation files.

**Comment by johnskydiver** [comment]
@CThompso3 I'm having difficulty reproducing your error.  Can you please try downloading the office source files using the "download" tab in the install toolkit as opposed to using the office setup file.  This will also auto populate the "source file path" on the final generate tab.  Please let me know the results.  Thanks.

John J.

**Comment by CThompso3** [comment]
@johnskydiver Well...I'm having difficulty reproducing my error as well. I just spent some time trying to recreate it and couldn't. I know I had a problem downloading files from the download tab (which is why I manually downloaded them); however, that is working fine.

I must have had something misconfigured in the XML file that I was trying to import. (I can't test that because it has since been deleted.) I apologize for the hassle.

**Comment by JimDimWit** [comment]
This defeats the purpose of using the Toolkit, but if you grab all the downloaded files from Setup.exe /download (there's only 8), put them in the same directory with your setup and configuration xml, you can build your own offline installer via batch.
I used this:
@echo off
::First part is to get admin rights
:: I don't remember where I got the elevation batch but credit doesn't go to me
:: BatchGotAdmin (Run as Admin code starts)
REM --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
echo Requesting administrative privileges...
goto UACPrompt
) else ( goto gotAdmin )
:UACPrompt
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
"%temp%\getadmin.vbs"
exit /B
:gotAdmin
if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
pushd "%CD%"
CD /D "%~dp0"
:: BatchGotAdmin (Run as Admin code ends)
:: Your codes should start from the following line
md C:\ODT2\Office\Data\16.0.9126.2275
copy /Y %~dp0\configuration.xml C:\ODT2\configuration.xml
copy /Y %~dp0\setup.exe C:\ODT2\setup.exe
copy /Y %~dp0\v64.cab C:\ODT2\Office\Data\v64.cab
copy /Y %~dp0\v64_16.0.9126.2275.cab C:\ODT2\Office\Data\v64_16.0.9126.2275.cab
copy /Y %~dp0\i640.cab C:\ODT2\Office\Data\16.0.9126.2275\i640.cab
copy /Y %~dp0\i641033.cab C:\ODT2\Office\Data\16.0.9126.2275\i641033.cab
copy /Y %~dp0\s640.cab C:\ODT2\Office\Data\16.0.9126.2275\s640.cab
copy /Y %~dp0\s641033.cab C:\ODT2\Office\Data\16.0.9126.2275\s641033.cab
copy /Y %~dp0\stream.x64.en-us.dat C:\ODT2\Office\Data\16.0.9126.2275\stream.x64.en-us.dat
copy /Y %~dp0\stream.x64.x-none.dat C:\ODT2\Office\Data\16.0.9126.2275\stream.x64.x-none.dat
C:\ODT2\setup.exe /configure C:\ODT2\configuration.xml
del /F /Q ODT2
exit

If you want it as a single file, make it into an executable with a compiler. I like Microsoft iExpress (normally lives at C:\Windows\System32\iexpress.exe).
