### ISSUE TITLE
Office 2016 ProPlus VL excluded apps not detected correctly

### ISSUE THREAD

**Issue by ariellov** [OfficeDev/Office-IT-Pro-Deployment-Scripts#207]
Hey, when tying to upgrade from office 2016 proplus regular install to office 365, excluded apps are not detected correctly when using automatic configuration.xml. Resulting configuration.xml is like this: 
`<Configuration>
  <Add OfficeClientEdition="32" Channel="Current">
    <Product ID="O365ProPlusRetail">
      <Language ID="en-us" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Word" />
    </Product>
  </Add>
  <Display Level="None" AcceptEULA="TRUE" />
  <Updates Channel="Current" Enabled="TRUE" />
</Configuration>`

all these exculdeapps are actually installed in office 2016. 
Adding    `             "16"
                {
                    $bitPath = '16.0'
                } `
to Generate-ODTConficurationXML.ps1 to line 1434 inside officeGetExcludedApps function seems to fix this issue, maybe that is all that is needed.

**Comment by AStigall** [comment]
@ariellov Great find! We'll get these updated.

**Comment by AStigall** [comment]
The scripts have been updated. Thank you for your feedback!
