### ISSUE TITLE
GetLanguagePacks function fails when Visual Studio 2015 Community is installed

### ISSUE THREAD

**Issue by ariellov** [OfficeDev/Office-IT-Pro-Deployment-Scripts#208]
Hey, if user has Visual Studio 2015 installed, GetLanguagePacks function breaks in Generate-ODTConfigurationXML.ps1. Error is "You cannot call a method on a null-valued expression"
It looks like $languageId variable is empty in this case and new-object creation throws an exception.
I've identified that these packages (from $DisplayName) result in empty $languageid:
Visual Studio 2015 Prerequisities - ENU Language Pack
Microsoft Visual Studio Team Foundation Server 2015 Update 3 CTP1 Office Integration Language Pack (x64) - ENU
Microsoft Portable Library Multi-Targeting Pack Language Pack - enu
Microsoft Visual Studo 2015 Test Tools Language Pack - ENU

These packages does not seems to have ShellUITransformLanguage registry value, and that's why it gets an error. 
Workaround is to modify line 1533 to `($DisplayName -match "Language Pack" -and $DisplayName -notmatch "Service Pack" -and $DisplayName -notmatch "Portable Library" -and $DisplayName -notmatch "Visual Studio")`

**Comment by AStigall** [comment]
@ariellov Thank you for the heads up! We will take a look and get the issue fixed asap.

**Comment by AStigall** [comment]
The scripts have been updated to exclude the Portable Library and Visual Studio.
