### ISSUE TITLE
Error Root element is missing

### ISSUE THREAD

**Issue by cobrien165** [OfficeDev/Office-IT-Pro-Deployment-Scripts#209]
Hello, I'm trying to use the install toolkit to manage my local ProPlus installation and am getting this error:
I've tried this on multiple computers. Any help would be appreciated.

![image](https://cloud.githubusercontent.com/assets/11300249/23558026/c0dd7160-fff7-11e6-9833-f36ffeb1bba7.png)

**Comment by johnskydiver** [comment]
@cobrien165 I am currently looking into this error.  Quick question for you, is the office install you're trying to manage with the toolkit the msi version of office 2016, or the click to run version?

**Comment by cobrien165** [comment]
It's been the click to run version on both computers I've tested.

**Comment by cobrien165** [comment]
It's been the click to run version on both computers I've tested.

**Comment by johnskydiver** [comment]
@cobrien165 can you tell me if you have values for regkeys VersionToReport and CDNBaseUrl and what those values are in any one of the following paths
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0\ClickToRun\Configuration
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\15.0\ClickToRun\Configuration

**Comment by cobrien165** [comment]
Under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration

I have:

VersionToReport: 16.0.7571.2109
CDNBaseUrl: http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60

**Comment by alex182** [comment]
@cobrien165  could you please check the %temp% directory on the machines that are having this issue for the following files and post their contents here, this is looking like it could be a XML parsing issue.  

- o365client_32bit.xml
- o365client_64bit.xml

also, please post the content of files that have the current year, month, day, and hour appended with "_32.xml" or "_64.xml" for example 2017378_32.xml or  2017378_64.xml in your %temp% directory.

**Comment by cobrien165** [comment]
There aren't any "o365client" xml files within that temp directory that I can find. I've attached a zip of the date-based xml files though.

[xml files.zip](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/files/824737/xml.files.zip)


.

**Comment by alex182** [comment]
@cobrien165  could you zip up the entire %temp% directory of one of the impacted machines and post it here?

**Comment by alex182** [comment]
ok, so it looks like your temp directory is missing a required xml file that is usually generated when you try managing your local installation.  My guess is that the function that generates that xml is erroring out but when that happens it swallows the error.  It shouldn't swallow the error anymore. 

Could you go to the Debug folder in [this zip](https://1drv.ms/u/s!Ao-e6Bvdq1OCgnppabpUPTCaZ3N3) and run the  OfficeProPlusInstallToolkit executable and let me know if a new error occurs and what the error is.

**Comment by RobertoHN** [comment]
I'm having the same issue. It was working before. I'm getting this message on three machines (the ones that I've tried so far).
```
`Root element is missing`
```
```
\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration
VersionToReport: 16.0.8326.2070
CDNBaseUrl: http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60
```
There are not xml files named like **o365client_32bit.xml** or **o365client_64bit.xml** but there are two xml files named [201711718_32.xml](https://pastebin.com/P23n5DWt) and [201711718_64.xml](https://pastebin.com/UpLDFFXp)

I also found a folder named OfficeProPlusInstallGeneratorLogs and inside has this OPPInstallGen-20171107185454.log file:
```
System.Xml.XmlException: Falta el elemento raíz.
   en System.Xml.XmlTextReaderImpl.Throw(Exception e)
   en System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   en System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   en System.Xml.XmlDocument.Load(XmlReader reader)
   en System.Xml.XmlDocument.LoadXml(String xml)
   en OfficeInstallGenerator.ConfigXmlParser.LoadXml(String xml)
   en MetroDemo.ExampleViews.StartView.<ManageLocal>d__15.MoveNext()
```
Thanks in advance. [LINK](https://pastebin.com/P23n5DWt)
