### ISSUE TITLE
The '<' operator is reserved for future use.

### ISSUE THREAD

**Issue by bwanapc** [OfficeDev/Office-IT-Pro-Deployment-Scripts#210]
Tried running on a Windows 7 Enterprise machine with Office 2016 Professional Plus MSI install.

Running PS as admin

command line I used - PS C:\temp\offscrub> . .\Remove-PreviousOfficeInstalls.ps1
Received this error - 
The '<' operator is reserved for future use.
At C:\temp\offscrub\Remove-PreviousOfficeInstalls.ps1:118 char:16
+ </a>          < <<<< a href="/explore" class="js-selected-navigation-item nav-item" data-ga-click="Header, click, Nav
 menu - item:explore" data-selected-links="/explore /trending /trending/developers /integrations /integrations/feature/
code /integrations/feature/collaborate /integrations/feature/ship /showcases /explore">
    + CategoryInfo          : ParserError: (<:OperatorToken) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported

**Comment by johnskydiver** [comment]
@bwanapc  Are you using the latest script?  Could you post a screenshot of line 118 of that Remove-PreviousOfficeInstalls script?  I'd like to see the specific line of code that is causing it to crash.

Thanks.
John J.

**Comment by AStigall** [comment]
@bwanapc Have you been able to get this working yet? We reviewed the scripts to make sure there weren't  any extra characters that shouldn't be there.

**Comment by sebirello** [comment]
Hi,

same error here, any solution yet?

Thanks!
Sebastian

**Comment by bwanapc** [comment]
![2017-03-16 10_43_12-q__2 microsoft_office removal_remove-previousofficeinstalls ps1 - notepad](https://cloud.githubusercontent.com/assets/26278561/24004868/7a937324-0a35-11e7-8308-aeeb24c69988.png)

**Comment by bwanapc** [comment]
I didn't get it working. I did end up using a different script.

**Comment by sebirello** [comment]
Hi,

I guess you saved the .html file instead of saving the code, please click the file then go to RAW and then download the site.

Altought I guess the PowerShell script is only for versions =< 2013, so you have to use the .vbs scripts.

Regards,
Sebastian
