### ISSUE TITLE
Invalid Command Line in SCCM For Program

### ISSUE THREAD

**Issue by coachphil71** [OfficeDev/Office-IT-Pro-Deployment-Scripts#211]
All
I''ve used the scripts to download my channel files and then created the programs, however the command line is being flagged as invalid for the programs. I have identifed this as the command line string being too long.

for example: %windir%\Sysnative\windowsPowershell\V1.0\Powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -WindowStyle Hidden -Command .\Update-Office365Anywhere.ps1 -WaitForUpdateToFinish $True -EnableUpdateAnywhere $True -ForceAppShutdown $True -UpdatePromptUser $True -DisplayLevel $False -UseScriptLocationAsUpdateSource $True

Also, should the script replace sysnatvie in the path with the correct architecture folder? I am having to manually replace sysnative with syswow64 to provide a valid path to powershell.exe

**Comment by AStigall** [comment]
@coachphil71 We are investigating. What OS version are you running the scripts from? Also, what version of ConfigMgr do you have?

**Comment by coachphil71** [comment]
Server 2012 r2 and SCCM 1606

**Comment by AStigall** [comment]
@coachphil71 I have been testing on Server 2012 R2 and System Center Configuration Manager 1606 and haven't been able to reproduce the errors you've run in to. Are there any other details you can give us? What steps do you take to reproduce the errors? Do any deployments work using the PowerShell scripts? For example, can you deploy Office or do you only get the error when pushing the Update-Office365Anywhere.ps1 script? Thanks!

**Comment by AStigall** [comment]
@coachphil71 There are likely limitations with the text field with the long command lines if you're trying to modify it manually. If you need to edit the command lines after using the scripts to create the programs we would need to consider a method to shorten the switch names.

**Comment by AStigall** [comment]
If this is still an issue please let us know. The commands may too long to modify or create manually from the console.
