### ISSUE TITLE
Remove Office Standard in a MSI file

### ISSUE THREAD

**Issue by isiess** [OfficeDev/Office-IT-Pro-Deployment-Scripts#212]
I'm creating an msi file with Office 365 Pro plus (files are embeded)  

Have we a solution to removed Office 2010 standard in the same package ? 
by adding somewhere a bit of xml file as 
 <Remove All="TRUE">
               <Product ID="standardww" >
               <Language ID="fr-fr" />
  </Product>
</Remove>

Thanks in advance

**Comment by johnskydiver** [comment]
@isiess We don't currently have a way to uninstall older versions off office through the toolkit, we do however, have deployment scripts via powershell which can remove older versions of office and install new versions of office if you're interested in going that route.  A good sample script to do this would be
https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/blob/master/Office-ProPlus-Deployment/Deploy-OfficeClickToRun/10-ExampleRemovePreviousAndUpgrade.ps1
and the sample is just that, it can be updated to suit your individual need.

Thanks.

John J.

**Comment by isiess** [comment]
Thanks for your reply !
