### ISSUE TITLE
Shim errors for the .net framework version and platform support.

### ISSUE THREAD

**Issue by isiess** [OfficeDev/Office-IT-Pro-Deployment-Scripts#213]
We build a Office 365 Pro plus msi deployment (with files embeded) 

When we try to install on Windows 7, it don't work and we are redirect on the following webSite 
https://support.microsoft.com/fr-fr/help/2715633/shim-errors-for-the-.net-framework-version-and-platform-support

Of course, .net 3.5.1 was already check on Windows Feature.

**Comment by johnskydiver** [comment]
@isiess Please install .net framework 4.5 or higher, this should clear up the issue.

Thanks.

John J.

**Comment by isiess** [comment]
.net was in the latest version (4.6.2) I've try to downgrade in 4.5, 
but it don't work also ... 
To be more precise : i'm running the msi with the following command msiexec.exe /i OfficeProPlus-embeded.msi /L*V Office.log 

In the Log, we see some different check and the creation of a folder with 2 flies : 
InstallOfficeProPlus.exe and a <guid>.xml files. 
When I try to run the .exe files, I see the "shim error"

**Comment by SriniRajagopal** [comment]
@isiess Can you please share screenshots/logs of the error message? It's getting a little difficult to replicate the issue as this could be environment dependent, and anything that you can provide us from script logs/event logs related to this would help. Also what all versions of .NET Framework is installed in this machine?
