### ISSUE TITLE
Bug in Office Click to Run XML Configurator

### ISSUE THREAD

**Issue by DianeFox** [OfficeDev/Office-IT-Pro-Deployment-Scripts#215]
The web page is returning an error, whether it is launched from Internet Explorer 11, Edge, Firefox or Chrome.  Running F12 Developer, shows the following:

HTML1300: Navigation occurred.
File: XmlEditor.html
HTML1416: Unexpected character in comment end. Expected "-->".
File: XmlEditor.html, Line: 871, Column: 69
HTML1416: Unexpected character in comment end. Expected "-->".
File: XmlEditor.html, Line: 881, Column: 82
HTML1509: Unmatched end tag.
File: XmlEditor.html, Line: 1434, Column: 25
HTML1509: Unmatched end tag.
File: XmlEditor.html, Line: 1445, Column: 25
HTML1509: Unmatched end tag.
File: XmlEditor.html, Line: 1484, Column: 25
SEC7118: XMLHttpRequest for https://microsoft-apiapp2f1d0adbd6b6403da68a8cd3e1888ddc.azurewebsites.net/api/Channel required Cross Origin Resource Sharing (CORS).
File: XmlEditor.html
SEC7120: Origin http://officedev.github.io not found in Access-Control-Allow-Origin header.
File: XmlEditor.html
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: XmlEditor.html

**Comment by AStigall** [comment]
Thank you for the detailed logs! We are working to resolve the issue as quickly as possible.

**Comment by johnskydiver** [comment]
issue has been resolved by one of our devs.  Thanks!

**Comment by DianeFox** [comment]
Just tested and error no longer appears - many thanks for the quick response!
