### ISSUE TITLE
Insider channels

### ISSUE THREAD

**Issue by miloush** [OfficeDev/Office-IT-Pro-Deployment-Scripts#216]
Could the `Change-OfficeChannel` script support the InsiderFast and InsiderSlow channels?

**Comment by johnskydiver** [comment]
@miloush The InsiderFast and InsiderSlow channels are internal channels and will not be supported in a public facing application.  We are dedicated to supporting the Current, Deferred, and FirstReleaseDeferred channels.  Thanks.
