### ISSUE TITLE
Bug: OffScrub03.vbs type ("2013" instead of "2003")

### ISSUE THREAD

**Issue by jrochet** [OfficeDev/Office-IT-Pro-Deployment-Scripts#218]
https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/blob/master/Office-ProPlus-Deployment/Remove-PreviousOfficeInstalls/OffScrub03.vbs

Line 5 should say "2003" not "2013":
' Script to remove (scrub) Office 2013 MSI products

**Comment by AStigall** [comment]
@jrochet Good catch! The files have been updated.
