### ISSUE TITLE
Remove Previous Office Installs not working with MainOfficeProduct

### ISSUE THREAD

**Issue by letsgoflyers81** [OfficeDev/Office-IT-Pro-Deployment-Scripts#220]
I've been working on using the Remove-PreviousOfficeInstalls.ps1 to remove various versions of Office 2010 and 2013 and it doesn't seem to work for MainOfficeProduct.  I have the Powershell script in the same directory as OffScrub10.vbs and OffScrub_O15msi.vbs. The script works with with no parameter to remove everything, and it works with setting ProductsToRemove to Project or Visio.  However when I set it to MainOfficeProduct, it doesn't uninstall anything.

Command: '.\Remove-PreviousOfficeInstalls.ps1 -ProductsToRemove MainOfficeProduct'
It displays: 'Detecting Office installs...'
But then the script finishes without doing anything.  There's no error so I don't think I'm entering the command or parameter wrong, so I'm not sure what the problem is.

Has anyone else seen this?  Thanks!

**Comment by AStigall** [comment]
@letsgoflyers81 when did you download the script? I uploaded an updated version of the script on Friday, April 14th.

**Comment by letsgoflyers81** [comment]
@AStigall I downloaded everything earlier in the week.  I'll try the newer version and see what happens, thanks.

**Comment by letsgoflyers81** [comment]
I just tried with the new script and the same thing happens.  It gets to "Detecting Office installs...", sits for a minute, then ends with no error.

**Comment by AStigall** [comment]
What version of Office is installed on the computer you are testing it on? I ran another test on a computer with Microsoft Office Professional Plus 2010 and it worked.

**Comment by letsgoflyers81** [comment]
@AStigall Office Professional Plus 2010 14.0.7015.1000 and Office Professional Plus 2013 15.0.4569.1506, both x86.

**Comment by AStigall** [comment]
@letsgoflyers81 interesting. If you right click the script and choose Edit, at line 1288 do you see this line:
`$ProductName = $MainOfficeProducts.DisplayName`

**Comment by letsgoflyers81** [comment]
@AStigall Yes I have that.  For what it's worth, all Office products in my environment are x86 but Windows is x64.  I don't know if that could throw off the version detection, but it works fine for Visio and Project (2010 Standard, 2010 Pro, and 2013 Pro).

**Comment by AStigall** [comment]
@letsgoflyers81 It shouldn't matter which bit you're using. It seems like there's an issue with the product detection issue when it runs the command `$OfficeProduct = GetProductName -ProductName MainOfficeProduct` at line 251. I'm guessing this is returning a null value for some reason.

Can you do me a quick favor? Open the registry editor on a computer you're testing this on and go to **HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall**. The reg key we need to find will look like Office14.PROPLUSR (for Office) or Office14.PROJPROR (for Project) or Office14.VISIO or something along those lines for each of your office products. Can you tell me what the names look like for you?

**Comment by letsgoflyers81** [comment]
@AStigall I had a feeling it was something like that, since without the parameter it'll uninstall everything without trying to detect specific products.  The registry has many entries for Office14 and Office15, a lot of which are for things like updates.  Do you only need one of each or do you need them all?

**Comment by AStigall** [comment]
Anything you can provide will help. For the primary Office products they should be like PRO or PROPLUS, along those lines. For example, you might see Office14.PRO.

**Comment by letsgoflyers81** [comment]
Here are the first entries for 2010 and 2013.
2010: {90140000-0011-0000-0000-0000000FF1CE}
2013: {90150000-0011-0000-0000-0000000FF1CE}

**Comment by AStigall** [comment]
Do you have entries below those that look how I described? The scripts will filter out registry entries that look like that. Those typically have a string inside called ParentKeyName with the entry I'm looking for, which should also be it's on key in the Uninstall location.

**Comment by letsgoflyers81** [comment]
@AStigall Sorry, the keys for 2010 and 2013 are Office14.PROPLUS and Office15.PROPLUS, respectively.

**Comment by AStigall** [comment]
@letsgoflyers81 I added some additional logging to the script to see if we can pin down what's going on or give us an indication. I've only updated the script located [here](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/tree/master/Office-ProPlus-Deployment/Remove-PreviousOfficeInstalls).

**Comment by letsgoflyers81** [comment]
@AStigall Thanks.  Sorry if this is a dumb question but how do I enable the logging?  It's not saving anything automatically and I'm not sure what command to use.

**Comment by AStigall** [comment]
@letsgoflyers81 I should have clarified. Logging is automatically enabled and will create a log file in the %windir%\Temp directory. The default log file name will have the date followed by OfficeDeploymentLog.

**Comment by letsgoflyers81** [comment]
Here's the log
[2017-04-18_OfficeDeploymentLog.txt](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/files/930560/2017-04-18_OfficeDeploymentLog.txt)

**Comment by letsgoflyers81** [comment]
@AStigall I ran it again for Visio and Project since I know they work, and the relevant lines from the log are below.  The main difference I see is that ProductName gets set to 'Visio' or 'Project' for those attempts, but for MainOfficeProduct it gets set to 'ProductName set to Microsoft Office Professional Plus 2010 Microsoft Office Professional Plus 2013 Microsoft Office Professional Plus 2010 Microsoft Office Professional Plus 2013'.  Maybe the way both products are there twice is causing a problem?  If you want another comparison I can see what it looks like with multiple versions of Visio or Project are installed (2010 and 2013).

4/18/2017 1:53:48 PM          1301           Remove-PreviousOfficeInstallstest.ps1                       ProductName set to Visio
4/18/2017 1:53:54 PM          265            Remove-PreviousOfficeInstallstest.ps1                       VisioProduct set to  
4/18/2017 1:53:54 PM          340            Remove-PreviousOfficeInstallstest.ps1                       Detecting Office installs...
4/18/2017 1:54:01 PM          429            Remove-PreviousOfficeInstallstest.ps1                       Removing Visio products...
4/18/2017 1:57:06 PM          1301           Remove-PreviousOfficeInstallstest.ps1                       ProductName set to Project
4/18/2017 1:57:11 PM          288            Remove-PreviousOfficeInstallstest.ps1                       ProjectProduct set to  
4/18/2017 1:57:11 PM          340            Remove-PreviousOfficeInstallstest.ps1                       Detecting Office installs...
4/18/2017 1:57:19 PM          482            Remove-PreviousOfficeInstallstest.ps1                       Removing Project products...

**Comment by AStigall** [comment]
@letsgoflyers81 Thanks for sharing that. The issue is probably because there are 2 versions of Office installed. I will need to adjust the scripts to take into account the possibility of more than 1 version of Office installed on the same computer.

In your case, are you wanting to remove both versions of Office, 2010 and 2013, or are you trying to preserve one over the other?

**Comment by letsgoflyers81** [comment]
You're welcome.  It's interesting because I think in my testing I was able to have two versions of Project or Visio and I could remove both of them.  I can try it again though, I may be mistaken.

I want to remove Office 2010 and 2013 in this case.  Our standard build has Office 2010 and also 2013 just for Lync.  They should both be removed when O365 is installed.

**Comment by letsgoflyers81** [comment]
@AStigall I was wrong about Visio and Project uninstalling if multiple versions are installed.  I installed Visio and Project Standard 2010, and Visio and Project Pro 2013, then ran the scripts for each of them.  The log below is when all versions were installed.  The log looks OK, but nothing uninstalled.

4/19/2017 10:33:24 AM         1301           Remove-PreviousOfficeInstallstest.ps1                       ProductName set to Visio
4/19/2017 10:33:30 AM         265            Remove-PreviousOfficeInstallstest.ps1                       VisioProduct set to    
4/19/2017 10:33:30 AM         340            Remove-PreviousOfficeInstallstest.ps1                       Detecting Office installs...
4/19/2017 10:33:38 AM         429            Remove-PreviousOfficeInstallstest.ps1                       Removing Visio products...
4/19/2017 10:35:59 AM         1301           Remove-PreviousOfficeInstallstest.ps1                       ProductName set to Project
4/19/2017 10:36:05 AM         288            Remove-PreviousOfficeInstallstest.ps1                       ProjectProduct set to    
4/19/2017 10:36:05 AM         340            Remove-PreviousOfficeInstallstest.ps1                       Detecting Office installs...
4/19/2017 10:36:13 AM         482            Remove-PreviousOfficeInstallstest.ps1                       Removing Project products...

Then I manually uninstalled one version of Visio and one version of Project and ran the scripts again.  The log looks the same, but this time the remaining versions were uninstalled.

4/19/2017 10:44:23 AM         1301           Remove-PreviousOfficeInstallstest.ps1                       ProductName set to Project
4/19/2017 10:44:29 AM         288            Remove-PreviousOfficeInstallstest.ps1                       ProjectProduct set to  
4/19/2017 10:44:29 AM         340            Remove-PreviousOfficeInstallstest.ps1                       Detecting Office installs...
4/19/2017 10:44:37 AM         482            Remove-PreviousOfficeInstallstest.ps1                       Removing Project products...
4/19/2017 10:46:24 AM         1301           Remove-PreviousOfficeInstallstest.ps1                       ProductName set to Visio
4/19/2017 10:46:29 AM         265            Remove-PreviousOfficeInstallstest.ps1                       VisioProduct set to  
4/19/2017 10:46:29 AM         340            Remove-PreviousOfficeInstallstest.ps1                       Detecting Office installs...
4/19/2017 10:46:37 AM         429            Remove-PreviousOfficeInstallstest.ps1                       Removing Visio products...

So it looks like whether it's MainOffice Product, Visio, or Project, the script doesn't work if there are multiple versions installed.

**Comment by AStigall** [comment]
@letsgoflyers81 Thanks for testing that! That's very helpful for us. We're addressing the issue and will post an update as soon as we have something ready.

**Comment by letsgoflyers81** [comment]
@AStigall You're very welcome, thanks for taking the time to work on this.  I'm eager to try what you come up with.

**Comment by letsgoflyers81** [comment]
@AStigall I'm sorry to be a pain, but I'm up against a wall to get my O365 packages done.  Have you made any progress yet?

**Comment by AStigall** [comment]
@letsgoflyers81 Working on it now. I should have something put together this afternoon.

**Comment by letsgoflyers81** [comment]
@AStigall Awesome thank you.

**Comment by AStigall** [comment]
@letsgoflyers81 I do have a working method now. I have been testing and will push an update this morning.

**Comment by AStigall** [comment]
@letsgoflyers81  I have created a new branch called Bugfix-RemovePreviousOfficeInstalls where I've pushed the updates too. This required a fairly significant amount of changes so I need to keep testing all scenarios before pushing it to the Master branch. On the GitHub homepage click the drop down that says **Branch: master** and select Bugfix-RemovePreviousOfficeInstalls. You can download the scripts after selecting that or you can copy the code from [here](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/tree/Bugfix-RemovePreviousOfficeInstalls/Office-ProPlus-Deployment/Remove-PreviousOfficeInstalls)

**Comment by letsgoflyers81** [comment]
@AStigall I just tested the new script and it worked for Office, Project, and Visio where 2010 and 2013 were both installed.  I have more scenarios to test since we have Project and Visio Standard and Professional in our environment, but so far so good.  Thank you so much for your help with this, I'll let you know how I make out with the rest of my testing.

**Comment by beanska** [comment]
Using the **Bugfix-RemovePreviousOfficeInstalls** branch worked for me but `Remove-PreviousOfficeInstalls` had to be used before `Install-OfficeClickToRun`. The function `GetProductName ` does not seem to handle having Office 2016 C2R and Office 2010 co-existing.

**Comment by AStigall** [comment]
Thank you @beanska. We'll take a look to see what's going on.

**Comment by jrochet** [comment]
Hi @AStigall .  I'm trying the Bugfix-RemovePreviousOfficeInstalls version of **Remove-PreviousOfficeInstalls**, with the -ProductsToRemove set to **MainOfficeProduct** and it does uninstall Office but it sends an error about Language packs removal:
```
PS > .\Remove-PreviousOfficeInstalls3.ps1 -ProductsToRemove MainOfficeProduct
Detecting Office installs...
        Removing  Microsoft Office Professional Plus 2010 ...
        Removing the language packs...
'/uninstall' is not recognized as an internal or external command,
operable program or batch file.
```
Any idea if I could just remove the language pack removal attempt or maybe just a typo somewhere?

**Comment by jrochet** [comment]
@beanska and @AStigall I believe I've found the problem with when you have 2016 click-to-run already installed before you try to use Remove-PreviousOfficeInstalls to remove a previous version.  It is the final else {throw that needs to be ommitted:
```
                                "16" {
                                    if($Remove2016Installs){
                                        if(!$isVisioC2R){
                                            $ActionFile = Join-Path -Path $ScriptPath -ChildPath $16MSIVBS
                                        } else {
                                            if($RemoveClickToRunVersions){
                                                Remove-OfficeClickToRun -C2RProductsToRemove "VisioProRetail","VisioProXVolume", "VisioStdXVolume"
                                            } else {
                                                WriteToLogFile -LNumber $(LINENUM) -FName $currentFileName -ActionError "Visio cannot be removed. Use the -RemoveClickToRunVersions parameter to remove Click-To-Run 2016 installs." -LogFilePath $LogFilePath
                                                throw "Visio cannot be removed. Use the -RemoveClickToRunVersions parameter to remove Click-To-Run 2016 installs."
                                            }
                                        }
                                    } else {
                                        WriteToLogFile -LNumber $(LINENUM) -FName $currentFileName -ActionError "Visio cannot be removed. Use the -RemoveClickToRunVersions and -Remove2016Installs parameters to remove Click-To-Run 2016 installs." -LogFilePath $LogFilePath
                                        throw "Visio cannot be removed. Use the -RemoveClickToRunVersions and -Remove2016Installs parameters to remove Click-To-Run 2016 installs."
                                    }
                                }
```
If you just comment out the two line in that final else statement (in each section (MainOfficeProduct, Visio, Project, AllOfficeProducts), the script will work as planned:
```
                                "16" {
                                    if($Remove2016Installs){
                                        if(!$c2rInstalled){
                                            $ActionFile = Join-Path -Path $ScriptPath -ChildPath $16MSIVBS
                                        } else {
                                            if($RemoveClickToRunVersions){
                                                Remove-OfficeClickToRun -C2RProductsToRemove $MainOfficeProduct.Name.Split('-')[0].Trim()
                                            } else {
                                                WriteToLogFile -LNumber $(LINENUM) -FName $currentFileName -ActionError "Office 2016 Click-To-Run cannot be removed. Use the -RemoveClickToRunVersions parameter to remove Click-To-Run 2016 installs." -LogFilePath $LogFilePath
                                                throw "Office 2016 Click-To-Run cannot be removed. Use the -RemoveClickToRunVersions parameter to remove Click-To-Run 2016 installs."
                                            }
                                        }
                                    } else {
                                        #WriteToLogFile -LNumber $(LINENUM) -FName $currentFileName -ActionError "Office 2016 Click-To-Run cannot be removed. Use the -RemoveClickToRunVersions and -Remove2016Installs parameters to remove Click-To-Run 2016 installs." -LogFilePath $LogFilePath
                                        #throw "Office 2016 Click-To-Run cannot be removed. Use the -RemoveClickToRunVersions and -Remove2016Installs parameters to remove Click-To-Run 2016 installs."
                                    }
                                }
```
There might be a clause where this is breaking some other functionality so it's definitely just a quick fix or workaround but maybe it will help to find the final resolution.

**Comment by jrochet** [comment]
PS, my updated version based on the **BugFix-RemovePreviousOfficeInstalls** version, including the commenting out fix from above is available for testing with:

[.README_Remove-PreviousOfficeInstalls.ps1.md](https://github.com/jrochet/OfficeDeployment/blob/master/.README_Remove-PreviousOfficeInstalls.ps1.md)
[Remove-PreviousOfficeInstalls.ps1](https://github.com/jrochet/OfficeDeployment/blob/master/Remove-PreviousOfficeInstalls.ps1)

**Comment by AStigall** [comment]
Thanks @jrochet !

**Comment by slaalaj** [comment]
I have the same issue, cannot remove only MainOfficeProduct, 
The script is working with Visio, Project or All Office without the parameter
