### ISSUE TITLE
Executing Remove-PreviousOfficeInstalls.ps1 from an UNC path return errors

### ISSUE THREAD

**Issue by Gatzu78** [OfficeDev/Office-IT-Pro-Deployment-Scripts#222]
Hello,
I am running the Remove-PreviousOfficeInstalls.ps1 from our company distribution point share.
This is the output:

Detecting Office installs...
        Removing all Office products...
'\\RSIS-EFESTO-DP\DP\OFFICE365\Scripts\Remove-PreviousOfficeInstalls'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'\\RSIS-EFESTO-DP\DP\OFFICE365\Scripts\Remove-PreviousOfficeInstalls'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

The Office I am trying to uninstall is 2013.
As you can see the execution complains two times that command prompt can't use UNC path.
At the end of script execution Office 2013 is actually removed from the target machine.

I know I could solve the issue mounting the share with NET USE, but my question is what is failing in the execution since at the end it works?

Thanks.
Regards.

**Comment by AStigall** [comment]
Nothing is failing, and unless you mapped the network path to a drive letter it will continue to show that error. However, the tasks that the scripts are executing are not affected by this.

**Comment by jrochet** [comment]
@Gatzu78  If you're calling the script itself from a UNC, chances are you also want to store the OffScrub***.vbs and other .exe's in a central UNC somewhere too.  That's what I wanted as well. I'm trying to maintain a copy of Remove-PreviousOfficeInstalls.ps1 that caters to the central UNC path so I can use the script as a GPO machine startup script.  My readme: [.README_Remove-PreviousOfficeInstalls.ps1.md](https://github.com/jrochet/OfficeDeployment/blob/master/.README_Remove-PreviousOfficeInstalls.ps1.md)

Only thing is, I'm surely going to be making changes over time and so I wouldn't come to depend on my version, but maybe just have a look for ideas so you can make one that works to your needs too.
