### ISSUE TITLE
Problems in Remove-PreviousOfficeInstalls.ps1

### ISSUE THREAD

**Issue by jrochet** [OfficeDev/Office-IT-Pro-Deployment-Scripts#225]
I've run into an issue with help from customers that I'm working with where Office 2013 Click-to-Run was not successfully uninstalling and what was left was that Office appears to be installed but none of the apps would launch, instead an error would occur (0xc0000005) [Same error as here](https://answers.microsoft.com/en-us/windows/forum/all/the-application-is-unable-to-start-correctly/bbb9c037-77b3-4fae-93b9-ded70f7f9a17).  After this the best solution to get back on track was the [Fixit tool](https://support.office.com/en-us/article/Uninstall-Office-from-a-PC-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8?ui=en-US&rs=en-US&ad=US) for completely cleaning Office off of the system.

What I found was that in the AllOfficeProducts section, unlike the MainOfficeProduct, Visio, and Project sections, OffScrubc2r.vbs is being called.  This seems to work fine for Office 2016 CTR, but not 2013.  In my repo, I've changed this so that even when specifying AllOfficeProducts, instead of calling OffScrubc2r.vbs, Remove-OfficeClickToRun function is called with -CTRProductsToRemove "All" specified.  I also had to add in 
```
if($product.ClickToRun -eq $true){
  $c2r2013Installed = $true
}
```
...into the "15" section because otherwise, Office 2013 CTR would never be detected as being installed.  You can see my commit against my copy [here](https://github.com/jrochet/OfficeDeployment/commit/b3689e851bea475c845133e526dd8abfd245533f).

**Comment by AStigall** [comment]
@jrochet Thank you for the comments and good details. We'll get this updated shortly.

**Comment by AStigall** [comment]
Updated the scripts
