### ISSUE TITLE
Name Too Long - Uninstall 

### ISSUE THREAD

**Issue by Romper** [OfficeDev/Office-IT-Pro-Deployment-Scripts#226]
I've tried everything to Uninstall this and failed.  It's the "name too long" error in Windows 7.   There either needs to be an Uninstall application or rename the files.  There are 30 of them or something.

**Comment by AStigall** [comment]
@Romper Which script in particular are you using and at what point do you get the character limit error?

**Comment by Romper** [comment]
Windows 7 64
I downloaded the ZIP from github.  I was trying to create a customized
version of Microsoft Office installation.  Gave up.  Tried to uninstall
OfficeDev/Office-IT-Pro etc from the Desktop where the WinRar folder Wizard
created it.  Also from the Desktop folder in Windows in C:\

Tried right click delete (name too long).  Tried empty folder and drag
(name too long).  Tried CMD but it kept saying it couldn't find the
folder.  Tried Revo and it "said" it would delete it on the next startup
but it never did.  I kept looking at the folders and I never could see
where the names were too long myself because I really thought about
renaming them individually by this point.  It just kept giving me the error
that there were 29 or 30 files "Would you like to skip or cancel"

I finally found *Fast Copy*  https://ipmsg.org/tools/fastcopy.html.en
after searching.  And that did it.  So I can't tell you exactly what files
were too long because I was able to remove it.

If you want me to, I can install it again and try to reproduce it for you.

**Comment by johnskydiver** [comment]
@Romper I've created a branch called BugFix-FilePathTooLong.  Use this branch and you shouldn't receive that error anymore.  I'm working on merging this branch into master shortly.

Thanks.
