### ISSUE TITLE
Problem with remove-officeclicktorun.ps1

### ISSUE THREAD

**Issue by greenrock2** [OfficeDev/Office-IT-Pro-Deployment-Scripts#229]
when i try to remove projectproretail using remove-officeclicktorun.ps1 with this command 👍 
**remove-OfficeClickToRun -C2RProductsToRemove projectproretail** 
the RemoveCTRConfig.xml generated is incomplete:

> `
> `
```

`Configuration>`
  <Remove>
  </Remove>
  <Display Level="FULL" AcceptEULA="TRUE" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>
```

> `

I have to dotsourcing of the 2 powershellscripts remove-officeclicktorun.ps1 and Remove-PreviousOfficeInstalls.ps1 :

```
Process {

    $scriptPath = "."

    if ($PSScriptRoot) {

        $scriptPath = $PSScriptRoot
    }
    else {

        $scriptPath = split-path -parent $MyInvocation.MyCommand.Definition
    }

    #Importing all required functions
    . $scriptPath\Remove-OfficeClickToRun.ps1
     . $scriptPath\Remove-PreviousOfficeInstalls.ps1
    
    
 



remove-OfficeClickToRun -C2RProductsToRemove projectproretail 

}

```
to generate the appropriate  RemoveCTRConfig.xml `👍
```
<Configuration>
  <Remove>
    <Product ID="projectproretail">
      <Language ID="en-us" />
      <Language ID="es-es" />
    </Product>
  </Remove>
  <Display Level="Full" AcceptEULA="TRUE" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>`
```

 because Get-ODTOfficeProductLanguages function is lacking in Remove-OfficeClickToRun.ps1 script.

But I have an other pb, when I try to launch the powershell script by an hta menu the  RemoveCTRConfig.xml generated is **still incomplete** like above. That is my biggest problem.
I launch it by this command 👍 `powershell.exe -executionpolicy bypass -nologo -noninteractive -windowstyle hidden -file "%~dp0remove-project.ps1"`

An error is also generated 👍 ```
![image](https://cloud.githubusercontent.com/assets/22954840/26829925/7f2aa0b0-4ac7-11e7-98fb-2f8804fc50b4.png)

```
odtGetOfficeLanguages function is lacking in the Remove-OfficeClickToRun.ps1 script
All the scripts have been stored in c:\temp\office365proplus

**Comment by AStigall** [comment]
@greenrock2 I have added all of the required functions to the Remove-OfficeClickToRun. I ran a test to remove ProjectProRetail and it is generating a good xml now.
