### ISSUE TITLE
Problem with Download-OfficeProPlusChannels

### ISSUE THREAD

**Issue by gallama1** [OfficeDev/Office-IT-Pro-Deployment-Scripts#230]
Form 14-Jun-17, the script fails to download the updates.
The error seems to be on the line 756, where is called "expand" command.
Here is the error that you get by running the script:
```
Get-Content : Cannot find path 'C:\Users\ADMIN~1.GAL\AppData\Local\Temp\ReleaseHistory.xml' because it does not exist.
At C:\OfficeUpdates\ToolKit\Download-OfficeProPlusChannels.ps1:759 char:23
+         [xml]$vdxml = Get-Content $baseCabFileName2
```

Original line 756:
`expand $destination2 "$env:TEMP\ReleaseHistory.xml" -f:"ReleaseHistory.xml" | Out-Null`
Fixed line 756:
` expand $destination2 "$env:TEMP" -f:"ReleaseHistory.xml" | Out-Null`

**Comment by alex182** [comment]
@gallama1  are you still encountering this issue?  I can't seem to be able to reproduce it.
