### ISSUE TITLE
1-ExampleDeployGeneric.ps1 - Update not running

### ISSUE THREAD

**Issue by klickundlos** [OfficeDev/Office-IT-Pro-Deployment-Scripts#231]
Hello,

i´m trying the example deployment scripts.
The script fails on my test systems with the following error:
"Update not running"
i´ve located that the Message originates from the "Install-OfficeClickToRun.ps1" file.

How can i get the script running? i´m running the script from the same location as the ODT setup.exe is located and the content for O365 was already downloaded to.

**Comment by AStigall** [comment]
@klickundlos It's difficult to understand what may be causing your issue without more details.
