### ISSUE TITLE
Generate-ODTConfigurationXML.ps1 - no output / no configuration file at all

### ISSUE THREAD

**Issue by klickundlos** [OfficeDev/Office-IT-Pro-Deployment-Scripts#232]
Hi,

when i try to run the Generate-ODTConfigurationXML.ps1 from the example scripts, i get zero output on any of my test systems (Office 2013, Windows 8, Windows 7 and Office 2016 on Windows 10).

We try to run the script with the "-targetfilepath" parameter but we get no output or the configuration xml.

Is that script even remotely working? How can we get it running?

**Comment by ColdFire1985** [comment]
Hi there, 
I had the same Problem. 

PS C:\WINDOWS\system32> Generate-ODTConfigurationXml | fl
PC104244: You cannot call a method on a null-valued expression.

Put some Strings in the Function `function GetLanguagePacks {` (autocad autodesk)

if($DisplayName -match "Language Pack" -and $DisplayName -notmatch "Service Pack" `
                                                   -and $DisplayName -notmatch "Portable Library" `
                                                   -and $DisplayName -notmatch "Visual Studio" `
                                                   -and $DisplayName -notmatch "AutoCAD" `
                                                   -and $DisplayName -notmatch "AutoDesk" `
                                                   -and $DisplayName -notmatch "Foundation Server" ){

This worked 4 me. Maybe you have other software called "Language Pack"

**Comment by AStigall** [comment]
@klickundlos Were you able to get this working? Do you have any other details that might help us figure out why the script isn't working for you?

**Comment by AStigall** [comment]
There are no existing issues with the Generate-ODTConfigurationXML script. Closing.
