### ISSUE TITLE
Wrong Product ID for Visio STD 2016 Volume License if you select a channel other than Current

### ISSUE THREAD

**Issue by TheBaban** [OfficeDev/Office-IT-Pro-Deployment-Scripts#233]
you will get:
Product ID="O365ProPlusRetail"

instead of:
Product ID="VisioStdXVolume"

If you select a different Channel than the default one.

**Comment by johnskydiver** [comment]
@TheBaban This issue has been reviewed and fixed.  The bug has been taken care of, and you'll see the changes reflected on the next release of the XML Editor.

**Comment by TheBaban** [comment]
Thank you  ;)
