### ISSUE TITLE
Generate-ODTConfigurationXML.ps1: Cannot process argument transformation on parameter 'SharedComputerLicensing'

### ISSUE THREAD

**Issue by appleoddity** [OfficeDev/Office-IT-Pro-Deployment-Scripts#234]
When I run the example script, 10-ExampleRemovePreviousAndUpgrade.ps1, I get the error above.

Upon further investigation I find that there is a duplicate function in both Generate-ODTConfigurationXML.ps1 and Edit-OfficeConfigurationFile.ps1.

That function, Set-ODTConfigProperties, is fundamentally different between the two files. Because the example script imports the Edit-OfficeConfigurationFile.ps1 file after the ODTConfigurationXML.ps1 file, the function is clobbered and causes the ODTConfigurationXML.ps1 file to fail when it attempts to call the above mentioned function.

This problem is only seen when the SharedComputerLicensing registry value exists.

From a closer look, it appears there is a lot of code duplication, and there are a lot of examples of functions being clobbered from one script to another. This package is in serious need of centralizing the functions in a shared library of some sort.

As a work around to this issue I renamed the function and function call to G_Set-ODTConfigProperties in ODTConfigurationXML.ps1. This is at the following line numbers: 490; 1868

**Comment by AStigall** [comment]
@appleoddity Thank you for letting us know about this. A fix has been pushed to correctly detect SharedComputerLicensing settings.
