### ISSUE TITLE
Exclude-Application in SharedFunctions.Ps1

### ISSUE THREAD

**Issue by Lt-Lemming** [OfficeDev/Office-IT-Pro-Deployment-Scripts#236]
I'm trying to write a script to install Project, Visio, Office365 or any combination of the three and always exclude OneDrive (generic, not OneDrive for Business) from being installed.

This works well if the main product is office, but due to the way Exclude-Application works it will ONLY exclude OneDrive (or any product) if the main product is Office365. 

Can you please change the script to allow this to be specified for any product? At the moment I am working around it by adding the line:

Set-ODTProductToAdd -TargetFilePath $targetFilePath -ProductId $product365 -ExcludeApps 'OneDrive' 

$Product365 being the product I am trying to install.

**Comment by AStigall** [comment]
@Lt-Lemming Why would you want to exclude OneDrive if you are not installing the base Office source files?

**Comment by Lt-Lemming** [comment]
Because as I have found, if you are installing just Project, or Just Visio.
The installer WILL install OneDrive unless you tell it not to.

We don't want to have OneDrive under any circumstances.

**Comment by AStigall** [comment]
That's really strange. We've never encountered that issue. I have tested using the most recent version of the ODT and OneDrive was never installed. Maybe you're running into a bug in the ODT? You can keep using the work around provided in your original post, of replace the Exclude-Applications function with the following:

    function Exclude-Applications() {
    [CmdletBinding()]
    param(
      [Parameter(Mandatory=$true)]
      [string] $TargetFilePath,

      [Parameter(Mandatory=$true)]
      [string[]] $ExcludeApps
    )
    process {

        $officeproducts = @("O365ProPlusRetail","O365BusinessRetail","VisioProRetail","ProjectProRetail","SPDRetail",
                            "VisioProXVolume","VisioStdXVolume","ProjectProXVolume","ProjectStdXVolume","InfoPathRetail",
                            "SkypeforBusinessEntryRetail","LyncEntryRetail","AccessRuntimeRetail")

        [bool]$excludedOneDrive = $false
        [bool]$isOffice = $false

        foreach($product in $officeproducts){
            if ((Get-ODTProductToAdd -TargetFilePath $targetFilePath -ProductId $product)) {
                if($product -eq "O365ProPlusRetail" -or $product -eq "O365BusinessRetail"){
                    Set-ODTProductToAdd -ProductId $product -TargetFilePath $targetFilePath -ExcludeApps $ExcludeApps | Out-Null
                } 
                
                foreach($app in $ExcludeApps){
                    if($app -eq "OneDrive"){  
                        Set-ODTProductToAdd -ProductId $product -TargetFilePath $targetFilePath -ExcludeApps $app | Out-Null  
                    }
                } 
            }
        }
    }
    }
