### ISSUE TITLE
-SharedComputerLicencing in Edit-OfficeConfigurationFile appears broken 

### ISSUE THREAD

**Issue by KonTheCat** [OfficeDev/Office-IT-Pro-Deployment-Scripts#237]
Setting the parameter -SharedComputerLicencing as 1 writes "TRUE" to the configuration.xml file and I got a shared licencing error on Server 2016 servers when trying to install with that configuration file. The permitted values for that parameter in the config file seem to be 1 and 0, per Microsoft documentation below. 

Offending line seems to be 2095, originally below like this: 
`< $SharedComputerLicensingElement.SetAttribute("Value", $SharedComputerLicensing.ToString().ToUpper()) | Out-Null >`
Thinking of having it be like this instead, to return the integer value of the boolean: 
`< $SharedComputerLicensingElement.SetAttribute("Value", [int]$SharedComputerLicensing) | Out-Null >`

Test with new line produces a configuration file with the value set to 1. 

https://support.office.com/en-us/article/Configuration-options-for-the-Office-2016-Deployment-Tool-d3879f0d-766c-469c-9440-0a9a2a905ca8?ui=en-US&rs=en-US&ad=US

`< <Property Name="SharedComputerLicensing" Value="0"/> >`
`<  <Property Name="SharedComputerLicensing" Value="1"/> >`

**Comment by AStigall** [comment]
We've corrected this, thank you.
