### ISSUE TITLE
Unable to use the toolkit - Urgent

### ISSUE THREAD

**Issue by lowwy78** [OfficeDev/Office-IT-Pro-Deployment-Scripts#240]
Hi, As soon as I press generate this occurs.

![screen shot 2017-07-06 at 11 25 40 am lawrence hanna](https://user-images.githubusercontent.com/29935191/27892046-d162bba2-6240-11e7-9ef2-3fb35c3a4716.png)

**Comment by alex182** [comment]
@lowwy78  can you tell me specifically what you are trying to do?  Are you generating an MSI or EXE?  Are you embedding files?  What options have you selected, what applications you are including/excluding, etc.
