### ISSUE TITLE
OffScrub | Add Removal of Scheduled Tasks: \Windows\Office

### ISSUE THREAD

**Issue by Arajdon** [OfficeDev/Office-IT-Pro-Deployment-Scripts#242]
Hi.

Had problems to install Office 2016 Business after uninstalling all Click to Run Packages.

There was a left over folder at Scheduled Task (Microsoft\Office)

After deleting the Folder, setup was successful.

Is it possible to add this into offscrub?

KR

**Comment by AStigall** [comment]
Unfortunately, we do not manage the Offscrub scripts. 

More information can be found [here](https://blogs.technet.microsoft.com/odsupport/2011/04/08/how-to-obtain-and-use-offscrub-to-automate-the-uninstallation-of-office-products/).
