### ISSUE TITLE
Problem with Remove-PreviousOfficeInstalls.ps1

### ISSUE THREAD

**Issue by jmillar64** [OfficeDev/Office-IT-Pro-Deployment-Scripts#243]
I've been testing the script and when removing the MainOfficeProducts there is a minor gap where with Office 2010 / Lync 2010 the products are removed but the Lync 2010 MUI isn't installed.  I'm guessing it's not being picked up because the IdentifyingNumber doesn't follow the same syntax as the other office products.

Description=Microsoft Lync 2010, MUI
IdentifyingNumber={CEECF731-3F08-4210-8073-7E87F58C01D3}
InstallDate=20160705
InstallLocation=
InstallState=5
Name=Microsoft Lync 2010, MUI
PackageCache=C:\windows\Installer\12d11.msi
SKUNumber=
Vendor=Microsoft Corporation
Version=4.0.7577.0

I'm not sure if this was brought up in the past or not but I'm trying to cover all of my basis on the product removal.  I've included an export of the uninstall regkey as well as reference.

Thanks,
[HKLM-Lync2010-MUI.txt](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/files/1183359/HKLM-Lync2010-MUI.txt)

Jeff

**Comment by AStigall** [comment]
We've pushed a fix to correctly detect and remove all Lync products.
