### ISSUE TITLE
Possible enhancement

### ISSUE THREAD

**Issue by jmillar64** [OfficeDev/Office-IT-Pro-Deployment-Scripts#244]
I had a an idea / suggestion which I thought could provide some benefit to this project.  Would it make sense to add additional logic to the OfficeRemoval script to write a registry key which would contain the Office Language pack which was installed prior to removal.  This could then be leveraged by the installation script to ensure during the upgrade / installation process that the appropriate language pack was included and would leave the device not requiring adding the language pack afterwards?  

Managing over 40k devices globally, it could reduce the need for creating for creating collections in SCCM or deployment tasks in various other deployment tools.

Thanks,
Jeff

**Comment by AStigall** [comment]
@jmillar64 That is a good suggestion and we capture the installed language packs into the configuration.xml files that get generated. Please, feel free to make any necessary changes that may have a beneficial impact on your deployment. You can make changes and submit a pull request if you'd like as well.
