### ISSUE TITLE
Configuration XML Editor leaving trailing space when specifying build version

### ISSUE THREAD

**Issue by tfurstms** [OfficeDev/Office-IT-Pro-Deployment-Scripts#246]
Repro Steps
* Start the Config XML Editor - https://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html
* On the Add Product page, scroll down and select a version (e.g., 1707, 1706)
* Scroll down and click Save
* On the right, the XML has a training space in the version parameter (e.g., Version="16.0.8229.2103 ")
* Below is an complete example
* Issue: When you the generated XML, it results in downloading the latest build instead of the specified build (no error message appears)
* Fix: Remove the trailing space

<Configuration>
    <Add OfficeClientEdition="32" Channel="Current" Version="16.0.8229.2103 ">
        <Product ID="O365ProPlusRetail">
            <Language ID="en-us" />
        </Product>
    </Add>
</Configuration>

**Comment by tfurstms** [comment]
Here is the example generated by the Config XML Editor...

``<Configuration>
    <Add  OfficeClientEdition="32" Channel="Current" Version="16.0.8229.2103 ">
        <Product ID="O365ProPlusRetail">
            <Language ID="en-us" />
        </Product>
    </Add>
</Configuration>``

**Comment by alex182** [comment]
@tfurstms  thanks for letting us know about this issue.  it has been resolved.

**Comment by tfurstms** [comment]
Thanks!
