### ISSUE TITLE
Please add IsDotSourced to Remove-OfficeClickToRun

### ISSUE THREAD

**Issue by TheRealBernie** [OfficeDev/Office-IT-Pro-Deployment-Scripts#248]
Adding IsDotSourced to Remove-OfficeClickToRun greatly helps and speeds up the process of using these scripts.

**Comment by AStigall** [comment]
@TheRealBernie We'll get that added. Thank you for the suggestion!

**Comment by AStigall** [comment]
This has been added, thank you.
