### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by KibagamiJubei** [OfficeDev/Office-IT-Pro-Deployment-Scripts#249]
Hello, 
Excellent project, I appreciate your hard work.
Few issues:

**Visio only** 
`PS C:\temp\removal> Remove-PreviousOfficeInstalls -ProductsToRemove Visio -RemoveClickToRunVersions $true -Remove2016Installs $true
Detecting Office installs...
        Removing Visio products...
Please wait while Microsoft Office 365 ProPlus - en-us is being uninstalled...
Write-Log : The term 'Write-Log' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\temp\removal\Remove-PreviousOfficeInstalls.ps1:796 char:9
+         Write-Log -Message $_.Exception.Message -severity 1 -componen ...
+         ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-Log:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Visio only, -RemoveClickToRunVersions and -Remove2016Installs set to true in the script**
`PS C:\temp\removal> Remove-PreviousOfficeInstalls -ProductsToRemove Visio
Detecting Office installs...
        Removing Visio products...
Visio cannot be removed. Use the -RemoveClickToRunVersions and -Remove2016Installs parameters to remove Click-To-Run
2016 installs.
At C:\temp\removal\Remove-PreviousOfficeInstalls.ps1:455 char:37
+ ...             throw "Visio cannot be removed. Use the -RemoveClickToRun ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Visio cannot be... 2016 installs.:String) [], RuntimeException
    + FullyQualifiedErrorId : Visio cannot be removed. Use the -RemoveClickToRunVersions and -Remove2016Installs param
   eters to remove Click-To-Run 2016 installs.`

**MainOfficeProduct**
`PS C:\temp\removal> Remove-PreviousOfficeInstalls -ProductsToRemove MainOfficeProduct -RemoveClickToRunVersions $true -R
emove2016Installs $true
Detecting Office installs...
Please wait while Microsoft Office 365 ProPlus - en-us is being uninstalled...
Write-Log : The term 'Write-Log' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\temp\removal\Remove-PreviousOfficeInstalls.ps1:797 char:9
+         Write-Log -Message $_.Exception.Message -severity 1 -componen ...
+         ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-Log:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**dot source issue - removed curly quotes around DefaultDisplayPropertySet to fix it**
`PS C:\temp\removal> . .\Remove-PreviousOfficeInstalls.ps1
At C:\temp\removal\Remove-PreviousOfficeInstalls.ps1:1352 char:123
+ ... ent.Automation.PSPropertySet(â€˜DefaultDisplayPropertySetâ€™,[string[ ...
+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingArgument`

Best regards,
KibagamiJubei

**Comment by KibagamiJubei** [comment]
*UPDATE*
Write-log is removed, but Visio doesn't get removed, nor any Office product. There is no error output in the console. Here is the log:
'Time                          Line Number    FileName                                                    Action
06/09/2017 15:00:29           1284           Remove-PreviousOfficeInstalls.ps1                           ProductName set to Visio
06/09/2017 15:00:30           253            Remove-PreviousOfficeInstalls.ps1                           VisioProduct set to @{DisplayName=Microsoft Visio Professional 2016 - en-us; Version=16; Name=VisioProXVolume - en-us}
06/09/2017 15:00:30           328            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...
06/09/2017 15:00:30           417            Remove-PreviousOfficeInstalls.ps1                           Removing Visio products...
06/09/2017 15:00:31           711            Remove-PreviousOfficeInstalls.ps1                           Please wait while Microsoft Office 365 ProPlus - en-us is being uninstalled...
06/09/2017 15:00:31           797            Remove-PreviousOfficeInstalls.ps1                           Exception calling "Start" with "1" argument(s): "The system cannot find the file specified"
06/09/2017 15:03:07           328            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...
06/09/2017 15:03:07           523            Remove-PreviousOfficeInstalls.ps1                           Removing all Office products...
06/09/2017 15:04:08           328            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...
06/09/2017 15:04:09           523            Remove-PreviousOfficeInstalls.ps1                           Removing all Office products...
'

Best regards,
KibagamiJubei

**Comment by alex182** [comment]
@KibagamiJubei  do you have the Office2016Setup.exe file in the same directory that you are running this script from?

**Comment by KibagamiJubei** [comment]
@alex182 noope, I don't have it. Is it somewhere on GitHub or I can get it from O2016 (MSI) DVD or its the O365 setup.exe?
