### ISSUE TITLE
Help or enhancement

### ISSUE THREAD

**Issue by frznto** [OfficeDev/Office-IT-Pro-Deployment-Scripts#250]
First want to say this is just awesome work. We are doing a big push at my office to uninstall all old Offices and update to Office 2016 (OEM not 365). Been trying to incorporate just the Removal-PreviousOfficeInstalls and create a single MSI that just runs this function as we already have a installer for Office 2016 and it looks like all of your example files are geared towards O365.

Cant use the function separately as we haven't gotten a CA setup and allowing signed scripts to run yet. Have tried even with a execution bypass and it either fails out or still calls for credentials. While still new to Powershell been using PowerShell Studio to help learn and try and build out a MSI that will let me do it but getting hung up at the dot call part of the function. Any help I could get from you guys would be awesome. 

Wants: Be able to run the Removal ps1 without having to do a dot call. This is with the defaults already edited in the ps1 to remove what we want.

**Comment by KibagamiJubei** [comment]
I am using it with AutoIT wrapper:

RegWrite("HKCU\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell", "ExecutionPolicy", "REG_SZ", "Unrestricted") => allows execution of scripts
	
DisableWow64FsRedirection() => disables the default fs redirection on 64 bit systems
	
Start("PowerShell.exe .\Remove_Previous_Versions\Remove-PreviousOfficeInstalls.ps1 -RemoveClickToRunVersions $true -Remove2016Installs $true -Force $true -ProductsToRemove AllOfficeProducts", $RETURN_CODE, "30m") => runs the script
	
EnableWow64FsRedirection() => enables the default fs redirection on 64 bit systems
	
RegWrite("HKCU\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell", "ExecutionPolicy", "REG_SZ", "RemoteSigned") => reverts the PowerShell execution of scripts policy
	
Run("%windir%\explorer.exe", "", "", "") => starts explorer.exe, as sometimes the OffScrub*.vbs files are killing it

;;; DISABLE THE DEFAULT FILE SYSTEM REDIRECTION TO x86 FOLDERS
Func DisableWow64FsRedirection()
	DllCall ("kernel32.dll", "int", "Wow64DisableWow64FsRedirection", "int", 1)
EndFunc

;;; ENABLE THE DEFAULT FILE SYSTEM REDIRECTION TO x86 FOLDERS
Func EnableWow64FsRedirection()
	DllCall ("kernel32.dll", "int", "Wow64DisableWow64FsRedirection", "int", 0)
EndFunc


Good luck :)

**Comment by frznto** [comment]
Hey want to say thanks for the response, been out hunting/camping for the last couple weeks. What language does the wrapper save this as, Windows script?

**Comment by KibagamiJubei** [comment]
@frznto The wrapper I am using is written in AutoIT. 
You probably don't need it, it's just illustrating the general idea:

1. Set this registry value to allow execution of PS scripts for the current user:
Path "HKCU\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell"
Name  "ExecutionPolicy"
Type "REG_SZ"
Value "Unrestricted"

2. Call PowerShell from your script with the following command:
PowerShell.exe .\Remove-PreviousOfficeInstalls.ps1 -RemoveClickToRunVersions $true -Remove2016Installs $true -Force $true -ProductsToRemove AllOfficeProducts

3. Set this value in your script to strengthen the security of PS scripts execution:
Path "HKCU\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell"
Name  "ExecutionPolicy"
Type "REG_SZ"
Value "RemoteSigned"

4. Install Office if required


In my usage scenario, the wrapper script sits in the same folder as the removal scripts and .EXE files.
It sets the PS execution policy, calls the script with parameters and then it reverts the PS execution policy and then it does other things, like install O365 from a sub-folder.
I am running it as administrator (right-click=> run as administrator) in manual usage or installing for system in SCCM.
In batch it should look something like this:

```
rem  Hides console output
@echo off

rem Clear the screen
cls 

rem Change the working directory to the directory from where the script runs
pushd %~dp0 

rem Allow execution of PS scripts
reg add HKCU\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell /v ExecutionPolicy /t REG_SZ /d Unrestricted 

rem Runs the script
start /wait PowerShell.exe .\Remove-PreviousOfficeInstalls.ps1 -RemoveClickToRunVersions $true -Remove2016Installs $true -Force $true -ProductsToRemove AllOfficeProducts ::runs the script

rem Reverts execution of PS scripts policy
reg add HKCU\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell /v ExecutionPolicy /t REG_SZ /d RemoteSigned

rem Will install Office, assuming your O365 install files are in a sub-folder, called O365_Installation_Files
start /wait .\O365_Installation_Files\setup.exe /configure configuration.xml

rem Return to the original working directory
popd

rem Exit the script
exit
```

I guess to put it in a single MSI, you would have to rewrite it in VB script or something although I see no benefit in creating MSI for this. Still, different organisations, different rules and requirements.
Good luck :)

**Comment by frznto** [comment]
Thanks for all of your help. Based upon your stuff I got something working. We are using Landesk which does allow for powershell commands (just not executing ps1's currently) to ran without receiving a CA warning; the ps command runs with already made CA. Below is the way I got it to work, as you can tell by the extended functions you described from your wrapper.

Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force
Set-Location -Path "C:\Program Files (x86)\LANDesk\LDClient\sdmcache\Packages$\Microsoft\Office\Remove-PreviousOfficeInstalls"
.\Remove-PreviousOfficeInstalls.ps1 -RemoveClickToRunVersions $true -Remove2016Installs $true -Force $true -ProductsToRemove AllOfficeProducts

**Comment by KibagamiJubei** [comment]
Hello, I am glad you figured it out. 
One recommendation - always revert the powershell execution policy. 
You are setting unrestricted policy for the machine scope and this poses a security risk. Set it to remote signed after Office cleanup. 

Best regards,
Kalin

**Comment by AStigall** [comment]
Great community work! Closing this issue.
