### ISSUE TITLE
Doesn't detect Office 2003

### ISSUE THREAD

**Issue by KibagamiJubei** [OfficeDev/Office-IT-Pro-Deployment-Scripts#253]
**Function result**
PS C:\Users\*\Documents> . .\Remove-PreviousOfficeInstalls.ps1
PS C:\Users\*\Documents> Get-OfficeVersion -ShowAllInstalledProducts | select *
ComputerName             : ******
InstallPath              : C:\Program Files (x86)\Microsoft Office
Version                  : 16.0.7766.2099
ClickToRunUpdateUrl      :
ClickToRunUpdatesEnabled : True
ClientCulture            : en-us
ClickToRun               : True
Bitness                  : 32-Bit
DisplayName              : Microsoft Office 365 ProPlus - en-us

**Registry**
PS C:\Users\*\Documents> reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Current
Version\Uninstall" /v DisplayName /t REG_SZ /s | findstr "Office"
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Visual Studio 2010 Tools for Office Run
time (x64)
    DisplayName    REG_SZ    Microsoft Visual Studio 2010 Tools for Office Runtime (x64)
    DisplayName    REG_SZ    Microsoft Office 365 ProPlus - en-us
    DisplayName    REG_SZ    Office 16 Click-to-Run Licensing Component
    DisplayName    REG_SZ    Office 16 Click-to-Run Extensibility Component 64-bit Registration
    DisplayName    REG_SZ    Microsoft Visual Studio 2010 Tools for Office Runtime (x64)

PS C:\Users\*\Documents> reg query "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Win
dows\CurrentVersion\Uninstall" /v DisplayName /t REG_SZ /s | findstr "Office"
    DisplayName    REG_SZ    Microsoft Office Professional Edition 2003
    DisplayName    REG_SZ    Microsoft Office File Validation Add-In
    DisplayName    REG_SZ    Office 16 Click-to-Run Extensibility Component
    DisplayName    REG_SZ    Office 16 Click-to-Run Localization Component
    DisplayName    REG_SZ    Microsoft Office Configuration Analyzer Tool 2.2

**Log**

Time                          Line Number    FileName                                                    Action
12/09/2017 10:51:02           327            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...

12/09/2017 10:51:03           522            Remove-PreviousOfficeInstalls.ps1                           Removing all Office products...

12/09/2017 11:11:09           1283           Remove-PreviousOfficeInstalls.ps1                           ProductName set to MainOfficeProduct

12/09/2017 11:11:10           239            Remove-PreviousOfficeInstalls.ps1                           OfficeProduct set to 

12/09/2017 11:11:10           327            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...

12/09/2017 11:11:10           335            Remove-PreviousOfficeInstalls.ps1                           Microsoft Office is not installed

12/09/2017 11:20:35           1283           Remove-PreviousOfficeInstalls.ps1                           ProductName set to Microsoft Office 365 ProPlus - en-us

12/09/2017 11:20:36           239            Remove-PreviousOfficeInstalls.ps1                           OfficeProduct set to @{DisplayName=Microsoft Office 365 ProPlus - en-us; Version=16; Name=O365ProPlusRetail - en-us}

12/09/2017 11:20:36           327            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...

12/09/2017 11:20:42           710            Remove-PreviousOfficeInstalls.ps1                           Please wait while Microsoft Office 365 ProPlus - en-us is being uninstalled...

12/09/2017 11:23:04           327            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...

12/09/2017 11:23:05           522            Remove-PreviousOfficeInstalls.ps1                           Removing all Office products...

12/09/2017 11:27:11           1283           Remove-PreviousOfficeInstalls.ps1                           ProductName set to MainOfficeProduct

12/09/2017 11:27:11           239            Remove-PreviousOfficeInstalls.ps1                           OfficeProduct set to 

12/09/2017 11:27:11           327            Remove-PreviousOfficeInstalls.ps1                           Detecting Office installs...

12/09/2017 11:27:12           335            Remove-PreviousOfficeInstalls.ps1                           Microsoft Office is not installed

**Comment by AStigall** [comment]
@KibagamiJubei We're investigating. Thank you for the good details!

**Comment by kevinblumenfeld** [comment]
I have experienced this as well.

**Comment by KibagamiJubei** [comment]
Tested today with the latest version and it seems to be working. Will do some more testing and confirm if its really functioning as expected.

**Comment by kevinblumenfeld** [comment]
I tested this within the month and still an issue.  Full disclosure, I am using this to do this remotely:

https://github.com/kevinblumenfeld/PSOfficeDeploy

**Comment by KibagamiJubei** [comment]
Moved to:
https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/issues/264
