### ISSUE TITLE
Error on the script released on 9-13

### ISSUE THREAD

**Issue by Grandizer1973** [OfficeDev/Office-IT-Pro-Deployment-Scripts#254]
I get the following output just trying to run the script with no perameters.  I put the errors in a text file because they weren't coming out right in here.  One error comes up a few times is:
The '<' operator is reserved for future use.
And there's a couple more at the bottom.

[OfficeRemovalError.txt](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/files/1301771/OfficeRemovalError.txt)

**Comment by AStigall** [comment]
@Grandizer1973 These errors are foreign to us and look like they are pulling in HTML. Are you running script from a PowerShell console? Did you download the scripts by cloning or downloading the zip file?

**Comment by Grandizer1973** [comment]
Closing my post in shame as I realize I did not pull down the script at all but the link to the script though it saved it as a PS1 file...  Thanks for taking the time to reply, I have downloaded the actual script.  Thank you for this, it's a huge time saver.
