### ISSUE TITLE
Branch Changes do not match ofl.cab

### ISSUE THREAD

**Issue by BigSteef** [OfficeDev/Office-IT-Pro-Deployment-Scripts#256]
a lot of files have been changed to include the new branch names SemiAnnual, SemiAnnualTargeted  etc.

the current ofl.cab (10:30 @15/09/2017) has the following branches

branch               URL                                                                   
------               ---                                                                   
FirstReleaseCurrent  http://officecdn.microsoft.com/pr/64256afe-f5d9-4f86-8936-8840a6a4f5be
Current              http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60
FirstReleaseDeferred http://officecdn.microsoft.com/pr/b8f9b850-328d-4355-9145-c59439a0c4cf
Deferred             http://officecdn.microsoft.com/pr/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114
Insiders             http://officecdn.microsoft.com/pr/64256afe-f5d9-4f86-8936-8840a6a4f5be
Monthly              http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60
Targeted             http://officecdn.microsoft.com/pr/b8f9b850-328d-4355-9145-c59439a0c4cf
Broad                http://officecdn.microsoft.com/pr/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114

**Comment by AStigall** [comment]
@BigSteef We are using the public facing names for the new channels:

Insiders = Monthly (Targeted)
Monthly = Monthly
Targeted = Semi-annual (Targeted)
Broad = Semi-annual
