### ISSUE TITLE
Language MatchOS does not include fallback option

### ISSUE THREAD

**Issue by TheBaban** [OfficeDev/Office-IT-Pro-Deployment-Scripts#257]
Using this editor, we cannot set a fallback value when chosing  MatchOS.
The ODT accept the current syntax:
<Language ID="MatchOS" Fallback="en-us" />

**Comment by alex182** [comment]
@TheBaban  we are using XML attributes described [here](https://support.office.com/en-us/article/Configuration-options-for-the-Office-2016-Deployment-Tool-d3879f0d-766c-469c-9440-0a9a2a905ca8)

**Comment by alex182** [comment]
@TheBaban we are using XML parameters/attributes described [here](https://support.office.com/en-us/article/Configuration-options-for-the-Office-2016-Deployment-Tool-d3879f0d-766c-469c-9440-0a9a2a905ca8)
