### ISSUE TITLE
Need to add PIDKEY option for Volume License product

### ISSUE THREAD

**Issue by TheBaban** [OfficeDev/Office-IT-Pro-Deployment-Scripts#258]
When deploying a VL product (C2R-P) we need to put the GVLK to activate using KMS.
This is documented in the following article:

https://support.office.com/en-gb/article/Use-the-Office-Deployment-Tool-to-install-volume-licensed-editions-of-Visio-2016-and-Project-2016-82691bd7-a3d5-47ca-8d8a-0ee43ec2c01f

The PIDKEY could also be used to deploy MAKKEY. so we should offer both chose.
pre-enter the correct GVLK to use for the product or ask to enter a MAKKEY.

**Comment by AStigall** [comment]
@TheBaban This is support in the XML Generator as well as the Edit-OfficeConfigurationFile script. In PowerShell, you will need to generate an xml file first. Then, use the cmdlets in Edit-OfficeConfigurationFile.ps1 to add the volume licensed editions of Visio and Project. For example:

`. .\Edit-OfficeConfigurationFile.ps1`

`Add-ODTProductToAdd -TargetFilePath $Configfile -ProductId ProjectProXVolume -PIDKEY xxxxx-xxxx-xxxx-xxxx-xxxxx`
