### ISSUE TITLE
Remove-PreviousOfficeInstalls error  "You cannot call a method on a null-valued expression" When no Office Installed

### ISSUE THREAD

**Issue by wongcarter** [OfficeDev/Office-IT-Pro-Deployment-Scripts#261]
This error occurs when you set $ProductsToRemove to "MainOfficeProduct" and Office is not installed at all.

Error occurs at line 1363, because Get-OfficeVersion returns a null value, and GetProductName is not set up to handle a null value from Get-OfficeVersion.

**Comment by AStigall** [comment]
We have added error handling if no product is found.
