### ISSUE TITLE
Unable to execute scripts or ps1 file

### ISSUE THREAD

**Issue by urep102030** [OfficeDev/Office-IT-Pro-Deployment-Scripts#271]
When trying to execute the "remove-previousofficeinstalls.ps1" file I am getting an "The '<' operator is reserved for future use." error. This happens with the scripts as well. I have downloaded the files from the repository as-is. Any ideas?

**Comment by AStigall** [comment]
@urep102030  Does it tell you what line the error is occurring at?

**Comment by urep102030** [comment]
Yes 127, character 20

**Comment by urep102030** [comment]
![screenshot_126](https://user-images.githubusercontent.com/32850991/31678976-bafb1df2-b33d-11e7-8cf9-6d9f0b8fdfd4.jpg)

**Comment by urep102030** [comment]
![screenshot_126](https://user-images.githubusercontent.com/32850991/31679118-29b61c74-b33e-11e7-93a1-9328922eacf4.jpg)

**Comment by snackeyez** [comment]
I just had the same issue when trying to run command directly from powershell. When I followed the authors directions and opened command prompt first --> type powershell press enter --> type . .\remove-previousofficeinstalls.ps1   it worked

**Comment by urep102030** [comment]
@snackeyez can you post a screenshot of how you are executing? This is not working for me, even using the cmd to go into powershell- I get the same error.
@AStigall any help is appreciated!

**Comment by snackeyez** [comment]
![image](https://user-images.githubusercontent.com/32884505/31692169-b3257dec-b366-11e7-8553-57a86e7f9460.png)

**Comment by urep102030** [comment]
![screenshot_131](https://user-images.githubusercontent.com/32850991/31692666-b5a7a3a4-b368-11e7-81ae-c7fccafde0e3.jpg)

@snackeyez I'm doing the same thing but no luck.. files were downloaded directly from here too, have not tried to modify them

**Comment by snackeyez** [comment]
Ohh... Did you happen to right click on the .vbs links then click "save link as" ? If you look at the ps1 code and see any < in there, it's html, not powershell.  Try clicking the link to the vbs code, then clicking raw.  Copy and paste the raw code into a document, then name it "Remove-PreviousOfficeInstalls.ps1" save. 
![image](https://user-images.githubusercontent.com/32884505/31692939-0c070b94-b36a-11e7-91aa-93a473aae84e.png)

**Comment by urep102030** [comment]
@snackeyez you're a lifesaver! That worked- another issue I ran into after the ps1 ran was a VBS script error. Had to save the VBS files with ANSI encoding- just in case anyone else runs into this! Thanks for all your help!
