### ISSUE TITLE
cscript Offscrub10.vbs /Q gives error VBScript runtime error: Object required: 'LogStream'

### ISSUE THREAD

**Issue by ecspresso** [OfficeDev/Office-IT-Pro-Deployment-Scripts#281]
Running Offscub10.vbs from command line with /Q (silent) parameter does not work.

```
C:\>cscript Offscrub10.vbs /Q
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Microsoft Customer Support Services - Office 2010 Removal Utility

Version:        2.10
64 bit OS:      True
Removal start:  2:09:51 AM
OS Details: Microsoft Windows 10 Enterprise Evaluation, SP 0, Version: 10.0.16299, Codepage: 1252, Country Code: 1, Language: 1033

C:\Offscrub10.vbs(4221, 5) Microsoft VBScript runtime error: Object required: 'LogStream'
```

Any idea on how to resolve this issue?

**Comment by beefcakenana** [comment]
+1 to this, I am having the same issue with all versions of the Offscrub files. I cannot find anything to fix this issue.

**Comment by hippman257** [comment]
The scrub scripts need to be run from an Administrator Command or Admin PowerShell prompt.

**Comment by Skatterbrainz** [comment]
Please port this to a PowerShell script and add #requires Administrator ?  That way we can deploy this more easily via things like Configuration Manager.
