### ISSUE TITLE
Link to Powershell for Office is broken

### ISSUE THREAD

**Issue by fiveninezero** [OfficeDev/Office-IT-Pro-Deployment-Scripts#31]
The link to Powershell for Office in README.MD is currently broken. It points to https://poweshell.office.com/. After fixing the typo, the url must also be changed, as attempting to browse https://powershell.office.com/ results in an ssl warning from your favourite browser because the cert is only valid for __*.azurewebsites.net__.

The link should point to http://powershell.office.com/.

**Comment by v-rusmit** [comment]
We have updated the link. We appreciate your feedback!
