### ISSUE TITLE
bug: ConfigMgr PowerShell Module assumed on C:

### ISSUE THREAD

**Issue by tylerco** [OfficeDev/Office-IT-Pro-Deployment-Scripts#40]
The script assumes that the Configuration Manager console and PS module are located on C drive. Please update to check if PS module has already been loaded or create a variable to define PSM location.

**Comment by v-rusmit** [comment]
Thank you for your feedback.  Currently we look for the PS module in the $env:ProgramFiles environmental variable but if I can see if SCCM was installed on another drive the script would fail.  We will review the issue and hopefully have a resolution shortly.

**Comment by tylerco** [comment]
Could we create an option to override? I believe this will block many organizations from utilizing this script.

**Comment by v-rusmit** [comment]
We've change the script to look in more locations for the PowerShell module.  We've also added a parameter SCCMPSModulePath to manually specify the path.  Thanks again for the feedback!
