### ISSUE TITLE
Placeholder text in script header

### ISSUE THREAD

**Issue by Rarsic** [OfficeDev/Office-IT-Pro-Deployment-Scripts#61]
Line 45 of the Copy-OfficeGPOSettings.ps1 script has what looks to be temporary placeholder help text: Additional explanation. Long and indepth examples should also go here.

imo you should replace that with a link to https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts

**Comment by v-rusmit** [comment]
I believe we included template information in the script. We have updated the script in both the Development and master branch. We appreciate your feedback.
