### ISSUE TITLE
Validation or FirstReleaseBusiness

### ISSUE THREAD

**Issue by Kazzan** [OfficeDev/Office-IT-Pro-Deployment-Scripts#68]
XML reference of Office Deployment Tool for Click-to-Run use for Updates and Add elements of XML configuration file value "Validation" for First Release for Current Branch for Business. But XML editor use value "FirstReleaseBusiness". Both of them work actually, but this should be clarified if someone want trust to consistent update Branches. Because what to set to GPO? This is text field, not drop down list.

**Comment by v-rusmit** [comment]
Thank you for you feedback.  It was originally called FirstReleaseBusiness but was changed to Validation.  Even though FirstReleaseBusiness still works we agree with you that it should be changed to reflect the what the documentation uses.  We will update the page as soon as we can.

**Comment by v-rusmit** [comment]
@Kazzan We have updated the Xml Editor site with the Validation branch option.  Thank you for your input!  http://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html

**Comment by Kazzan** [comment]
@v-rusmit Thanks! If you have also option to make suggestion also to GPO integration team it will be nice for IT Pro.
