### ISSUE TITLE
#feature Generate-ODTConfigurationXML: Capture older Office installation

### ISSUE THREAD

**Issue by manoth-msft** [OfficeDev/Office-IT-Pro-Deployment-Scripts#76]
Feature request: The usefullness of the script could be expanded by providing two modes of operation: One captures the current state of Office 365 ProPöus (implemented), the other one captures the state of an older veriosn of Office (e.g. Office 2010 MSI) and creates a coressponding configuration.xml.

Example: Office 2010 Professional Plus as well as Project 2010 (both x86) are installed on a machine, both with two language packs, but the Access 2010 feature of Office 2010 is not installed. When you run GenerateODT with a new "captureoldversion=14" switch it will generate a configuration.xml, which contains two Add-sections (one for O365ProPlusRetail, one for Project365Retail, both x86), has Exclude App ID=Access set as well as the two language packs.

Most customer projects want to start with a like-for-like apprioach, this addition to the script would help.

**Comment by AStigall** [comment]
Thank you for your feedback. We have added functionality that supports this scenario. There is a function called officeGetExcludedApps that will run if previous versions of Office are installed. If an app is not detected in this function it will be added to the excluded list.
