### ISSUE TITLE
Office Telemetry tags script

### ISSUE THREAD

**Issue by pretzer** [OfficeDev/Office-IT-Pro-Deployment-Scripts#77]
The following script is used to assign 'tags' for Office Telemetry: https://gallery.technet.microsoft.com/Add-Tags-Labels-for-Office-09c81574

It is officially advertised on the respective TechNet article for Office Telemetry here: https://technet.microsoft.com/en-us/library/ff394407(v=office.16).aspx

It would be nice if it could be ported to Powershell and updated to support Office 2016 while adding it to this GitHub project. Thank you!

**Comment by v-rusmit** [comment]
Thanks for suggestion.  We will definitely take a look at this.

**Comment by johnskydiver** [comment]
@pretzer I've ported the script to powershell and added it to the development branch under https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/tree/Development/Office-ProPlus-Management/Add-TelemetryTags
Thanks.
