### ISSUE TITLE
System.String error. 

### ISSUE THREAD

**Issue by jamiewhitehead** [OfficeDev/Office-IT-Pro-Deployment-Scripts#89]
Hi Russell. 
First off, thanks for such an awesome script. I ran it in my test lab and all of the ADMX settings came across. However, I did have some GP push items in there that did not get copied over. I did note that there was a couple of system.string errors that occurred that may be related to this. 

Method invocation failed because [System.String] does not contain a method named 'RemoveAll'
At C:\temp\CopyOfficeGPO2013to2016\Copy-OfficeGPOSettings.ps1:866 char:17

Method invocation failed because [System.String] does not contain a method named 'RemoveAll'.
At C:\temp\CopyOfficeGPO2013to2016\Copy-OfficeGPOSettings.ps1:867 char:17

Cheers.

**Comment by v-rusmit** [comment]
Thank you for your feedback! We will take a look at the string errors. Can you provide some specifics on the Push items that didn't come over.  That would help us to figure out what we are missing.

**Comment by jamiewhitehead** [comment]
Not a problem.
Interestingly, i reran the script with the push items removed and the same error occurred. so it might not be the push items that are a problem. I have attached the reports of the original Source and target policies so you can check out the push items anyway. 

[GPO_reports.zip](https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/files/162980/GPO_reports.zip)
 
Also, I am a bit intrigued as to why, in this section, 
$Paths = [string]"$sysvolDir\$domain\Policies\{$ID}\User\Registry.pol", 
                     "$sysvolDir\$domain\Policies\{$ID}\Machine\Registry.pol";
    $commentPaths = ("$sysvolDir\$domain\Policies\{$ID}\User\comment.cmtx",
                     "$sysvolDir\$domain\Policies\{$TargetID}\User\comment.cmtx"),
                     ("$sysvolDir\$domain\Policies\{$ID}\Machine\comment.cmtx",
                     "$sysvolDir\$domain\Policies\{$TargetID}\Machine\comment.cmtx");
the $ID and $targetID are doubled up for $commentPaths and not for $Paths. The doubling up also does not seem to fit how it the Array elements for $commentPaths is used around line 858 onwards. But i could be competely wrong...

**Comment by AStigall** [comment]
@jamiewhitehead is this still an issue? Please let us know if we need to dig further into the issue.

**Comment by AStigall** [comment]
@jamiewhitehead Please let us know if this is still an issue and we can revisit.

**Comment by jamiewhitehead** [comment]
Hi,

to be honest, I have not used the script for 4 months or so now. It was
certainly useful at the time, but most of my customers are on Office 2016
now.

Cheers.
