### ISSUE TITLE
When choosing "sign installer" the "valid from" date on the certificate is in the future

### ISSUE THREAD

**Issue by dapozt** [OfficeDev/Office-IT-Pro-Deployment-Scripts#95]
When choosing "sign installer" the "valid from" date on the code sign certificate is a future date. I just generated one using the Install Toolkit on 12th of April 2016 but the code sign certificate tells me the certificate is valid **from** 4th of November 2016. 

Could this be a regional date/time issue? In Europe day/month is used, while in US month/day.

**Comment by v-rusmit** [comment]
Thank you for your feedback.  We believe we have a fix for this issue and should have it posted shortly.

**Comment by v-rusmit** [comment]
We posted an update and now the signing certificate date issue should be resolved.
