### ISSUE TITLE
object reference not set to an instance of an object when trying to download 64bit

### ISSUE THREAD

**Issue by lwears** [OfficeDev/Office-IT-Pro-Deployment-Scripts#98]
object reference not set to an instance of an object when trying to download 64bit Office365ProPlus - current branch
32 bit downloads fine
I seem to be having a lot of trouble deploying 64bit in general. Why 64bit? We currently use 64bit 2010 and would like to keep it the same.
let me know if anyone knows anything about this!

**Comment by v-rusmit** [comment]
What script were you using when you received the error?

**Comment by lwears** [comment]
![screen shot 2016-04-27 at 10 25 39](https://cloud.githubusercontent.com/assets/13499003/14846005/d16562a2-0c61-11e6-9853-e574cf9c89db.png)

looks like the program has been updated since i last tried. The 64Bit files now download and i can create both msi and exe files. However if I select to embed the installation files I get the same "object reference not set to an instance of an object"'

I am unsure what you mean with which script i am using. I am using the program you can see in the screenshot. Thanks for your assistance.

**Comment by xtozi** [comment]
Any update on this issue as I'm also getting the same "object reference not set to an instance of an object" if I select to embed office installation files.

**Comment by alex182** [comment]
We have posted a new version of the install toolkit which addressed this issue.  We will leave this issue open for the next 3 days.  If the issue persists please let us know and we will revisit the problem asap.  Thanks!
