### ISSUE TITLE
Office 2016 Standard version

### ISSUE THREAD

**Issue by hammuh** [OfficeDev/Office-IT-Pro-Deployment-Scripts#99]
dear,

I'm using Office 2016 Standard version. I cannot get the script to run. Please help to verify which Product ID should i use for Office 2016 Standard Version. 
![office2016](https://cloud.githubusercontent.com/assets/18480330/14556347/68d094b8-032a-11e6-90c7-8ff40ae65951.jpg)

**Comment by johnskydiver** [comment]
Can you please provide additional information so I can better assist on this issue?  It would be helpful to know the source of Office 2016 standard you're using to deploy with, and which script you're trying to use to get it to run.  Thanks.
